//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Arena.proto
// Note: requires additional types generated from: Base.proto
namespace fogs.proto.msg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SaveDefenceArrayReq")]
  public partial class SaveDefenceArrayReq : global::ProtoBuf.IExtensible
  {
    public SaveDefenceArrayReq() {}
    
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.SoldierList> _defence_soldiers = new global::System.Collections.Generic.List<fogs.proto.msg.SoldierList>();
    [global::ProtoBuf.ProtoMember(1, Name=@"defence_soldiers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.SoldierList> defence_soldiers
    {
      get { return _defence_soldiers; }
    }
  
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.EquipList> _defence_equips = new global::System.Collections.Generic.List<fogs.proto.msg.EquipList>();
    [global::ProtoBuf.ProtoMember(2, Name=@"defence_equips", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.EquipList> defence_equips
    {
      get { return _defence_equips; }
    }
  
    private int _combat_power = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"combat_power", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int combat_power
    {
      get { return _combat_power; }
      set { _combat_power = value; }
    }
    private int _pettypeid = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"pettypeid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int pettypeid
    {
      get { return _pettypeid; }
      set { _pettypeid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SaveDefenceArrayResp")]
  public partial class SaveDefenceArrayResp : global::ProtoBuf.IExtensible
  {
    public SaveDefenceArrayResp() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int _combat_power = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"combat_power", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int combat_power
    {
      get { return _combat_power; }
      set { _combat_power = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnterArenaLobbyReq")]
  public partial class EnterArenaLobbyReq : global::ProtoBuf.IExtensible
  {
    public EnterArenaLobbyReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnterArenaLobbyResp")]
  public partial class EnterArenaLobbyResp : global::ProtoBuf.IExtensible
  {
    public EnterArenaLobbyResp() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int _rank = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int rank
    {
      get { return _rank; }
      set { _rank = value; }
    }
    private int _today_times = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"today_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int today_times
    {
      get { return _today_times; }
      set { _today_times = value; }
    }
    private int _buy_times = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"buy_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int buy_times
    {
      get { return _buy_times; }
      set { _buy_times = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.ArenaPlayer> _opponents = new global::System.Collections.Generic.List<fogs.proto.msg.ArenaPlayer>();
    [global::ProtoBuf.ProtoMember(5, Name=@"opponents", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.ArenaPlayer> opponents
    {
      get { return _opponents; }
    }
  
    private int _next_tick = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"next_tick", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int next_tick
    {
      get { return _next_tick; }
      set { _next_tick = value; }
    }
    private uint _refresh_times = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"refresh_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint refresh_times
    {
      get { return _refresh_times; }
      set { _refresh_times = value; }
    }
    private uint _best_rank = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"best_rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint best_rank
    {
      get { return _best_rank; }
      set { _best_rank = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.SoldierList> _defence_soldiers = new global::System.Collections.Generic.List<fogs.proto.msg.SoldierList>();
    [global::ProtoBuf.ProtoMember(9, Name=@"defence_soldiers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.SoldierList> defence_soldiers
    {
      get { return _defence_soldiers; }
    }
  
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.EquipList> _defence_equips = new global::System.Collections.Generic.List<fogs.proto.msg.EquipList>();
    [global::ProtoBuf.ProtoMember(10, Name=@"defence_equips", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.EquipList> defence_equips
    {
      get { return _defence_equips; }
    }
  
    private int _defence_combat_power = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"defence_combat_power", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int defence_combat_power
    {
      get { return _defence_combat_power; }
      set { _defence_combat_power = value; }
    }
    private int _pettypeid = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"pettypeid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int pettypeid
    {
      get { return _pettypeid; }
      set { _pettypeid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StartArenaReq")]
  public partial class StartArenaReq : global::ProtoBuf.IExtensible
  {
    public StartArenaReq() {}
    
    private uint _charid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"charid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charid
    {
      get { return _charid; }
      set { _charid = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.SoldierList> _attack_soldiers = new global::System.Collections.Generic.List<fogs.proto.msg.SoldierList>();
    [global::ProtoBuf.ProtoMember(2, Name=@"attack_soldiers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.SoldierList> attack_soldiers
    {
      get { return _attack_soldiers; }
    }
  
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.EquipList> _attack_equips = new global::System.Collections.Generic.List<fogs.proto.msg.EquipList>();
    [global::ProtoBuf.ProtoMember(3, Name=@"attack_equips", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.EquipList> attack_equips
    {
      get { return _attack_equips; }
    }
  
    private int _type = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _rank_num = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"rank_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint rank_num
    {
      get { return _rank_num; }
      set { _rank_num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StartArenaResp")]
  public partial class StartArenaResp : global::ProtoBuf.IExtensible
  {
    public StartArenaResp() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private fogs.proto.msg.ArenaPlayer _opponent = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"opponent", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.ArenaPlayer opponent
    {
      get { return _opponent; }
      set { _opponent = value; }
    }
    private int _time = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int time
    {
      get { return _time; }
      set { _time = value; }
    }
    private int _today_times = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"today_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int today_times
    {
      get { return _today_times; }
      set { _today_times = value; }
    }
    private fogs.proto.msg.Attribute _hero_attr = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"hero_attr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.Attribute hero_attr
    {
      get { return _hero_attr; }
      set { _hero_attr = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ArenaRewardReq")]
  public partial class ArenaRewardReq : global::ProtoBuf.IExtensible
  {
    public ArenaRewardReq() {}
    
    private fogs.proto.msg.ArenaResult _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.ArenaResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int _key = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int key
    {
      get { return _key; }
      set { _key = value; }
    }
    private string _sign = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"sign", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sign
    {
      get { return _sign; }
      set { _sign = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ArenaRewardResp")]
  public partial class ArenaRewardResp : global::ProtoBuf.IExtensible
  {
    public ArenaRewardResp() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private fogs.proto.msg.DropList _drop_list = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"drop_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.DropList drop_list
    {
      get { return _drop_list; }
      set { _drop_list = value; }
    }
    private int _rank = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int rank
    {
      get { return _rank; }
      set { _rank = value; }
    }
    private fogs.proto.msg.ArenaResult _arena_result;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"arena_result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.ArenaResult arena_result
    {
      get { return _arena_result; }
      set { _arena_result = value; }
    }
    private int _diamond = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int diamond
    {
      get { return _diamond; }
      set { _diamond = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RefreshOpponentsReq")]
  public partial class RefreshOpponentsReq : global::ProtoBuf.IExtensible
  {
    public RefreshOpponentsReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RefreshOpponentsResp")]
  public partial class RefreshOpponentsResp : global::ProtoBuf.IExtensible
  {
    public RefreshOpponentsResp() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.ArenaPlayer> _opponents = new global::System.Collections.Generic.List<fogs.proto.msg.ArenaPlayer>();
    [global::ProtoBuf.ProtoMember(2, Name=@"opponents", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.ArenaPlayer> opponents
    {
      get { return _opponents; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ClearArenaCDReq")]
  public partial class ClearArenaCDReq : global::ProtoBuf.IExtensible
  {
    public ClearArenaCDReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ClearArenaCDResp")]
  public partial class ClearArenaCDResp : global::ProtoBuf.IExtensible
  {
    public ClearArenaCDResp() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private uint _diamond = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint diamond
    {
      get { return _diamond; }
      set { _diamond = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddArenaTimesReq")]
  public partial class AddArenaTimesReq : global::ProtoBuf.IExtensible
  {
    public AddArenaTimesReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddArenaTimesResp")]
  public partial class AddArenaTimesResp : global::ProtoBuf.IExtensible
  {
    public AddArenaTimesResp() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int _diamond = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int diamond
    {
      get { return _diamond; }
      set { _diamond = value; }
    }
    private int _today_times = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"today_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int today_times
    {
      get { return _today_times; }
      set { _today_times = value; }
    }
    private int _buy_times = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"buy_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int buy_times
    {
      get { return _buy_times; }
      set { _buy_times = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ArenaRankListReq")]
  public partial class ArenaRankListReq : global::ProtoBuf.IExtensible
  {
    public ArenaRankListReq() {}
    
    private int _page = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"page", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int page
    {
      get { return _page; }
      set { _page = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ArenaRankListResp")]
  public partial class ArenaRankListResp : global::ProtoBuf.IExtensible
  {
    public ArenaRankListResp() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.ArenaPlayer> _rank_list = new global::System.Collections.Generic.List<fogs.proto.msg.ArenaPlayer>();
    [global::ProtoBuf.ProtoMember(2, Name=@"rank_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.ArenaPlayer> rank_list
    {
      get { return _rank_list; }
    }
  
    private int _page = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"page", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int page
    {
      get { return _page; }
      set { _page = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ArenaRecordReq")]
  public partial class ArenaRecordReq : global::ProtoBuf.IExtensible
  {
    public ArenaRecordReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ArenaRecordResp")]
  public partial class ArenaRecordResp : global::ProtoBuf.IExtensible
  {
    public ArenaRecordResp() {}
    
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.ArenaRecord> _records = new global::System.Collections.Generic.List<fogs.proto.msg.ArenaRecord>();
    [global::ProtoBuf.ProtoMember(1, Name=@"records", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.ArenaRecord> records
    {
      get { return _records; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ArenaChallengeReq")]
  public partial class ArenaChallengeReq : global::ProtoBuf.IExtensible
  {
    public ArenaChallengeReq() {}
    
    private uint _charid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"charid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charid
    {
      get { return _charid; }
      set { _charid = value; }
    }
    private uint _rank_num = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"rank_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint rank_num
    {
      get { return _rank_num; }
      set { _rank_num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ArenaChallengeResp")]
  public partial class ArenaChallengeResp : global::ProtoBuf.IExtensible
  {
    public ArenaChallengeResp() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"ArenaResult")]
    public enum ArenaResult
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"AR_WIN", Value=1)]
      AR_WIN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AR_LOSE", Value=2)]
      AR_LOSE = 2
    }
  
}