//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: CrossServerWar.proto
// Note: requires additional types generated from: Base.proto
namespace fogs.proto.msg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnterCrossServerWarReq")]
  public partial class EnterCrossServerWarReq : global::ProtoBuf.IExtensible
  {
    public EnterCrossServerWarReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnterCrossServerWarResp")]
  public partial class EnterCrossServerWarResp : global::ProtoBuf.IExtensible
  {
    public EnterCrossServerWarResp() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.TileInfo> _tileinfo = new global::System.Collections.Generic.List<fogs.proto.msg.TileInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"tileinfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.TileInfo> tileinfo
    {
      get { return _tileinfo; }
    }
  
    private uint _game_state = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"game_state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint game_state
    {
      get { return _game_state; }
      set { _game_state = value; }
    }
    private uint _time_battle = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"time_battle", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint time_battle
    {
      get { return _time_battle; }
      set { _time_battle = value; }
    }
    private uint _time_cd = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"time_cd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint time_cd
    {
      get { return _time_cd; }
      set { _time_cd = value; }
    }
    private uint _union_goods = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"union_goods", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint union_goods
    {
      get { return _union_goods; }
      set { _union_goods = value; }
    }
    private uint _game_times = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"game_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint game_times
    {
      get { return _game_times; }
      set { _game_times = value; }
    }
    private uint _buy_times = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"buy_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint buy_times
    {
      get { return _buy_times; }
      set { _buy_times = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TileInfo")]
  public partial class TileInfo : global::ProtoBuf.IExtensible
  {
    public TileInfo() {}
    
    private uint _tile_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tile_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint tile_id
    {
      get { return _tile_id; }
      set { _tile_id = value; }
    }
    private string _tile_union_name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"tile_union_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tile_union_name
    {
      get { return _tile_union_name; }
      set { _tile_union_name = value; }
    }
    private uint _owner_typ = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"owner_typ", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint owner_typ
    {
      get { return _owner_typ; }
      set { _owner_typ = value; }
    }
    private uint _border_type = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"border_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint border_type
    {
      get { return _border_type; }
      set { _border_type = value; }
    }
    private uint _turns = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"turns", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint turns
    {
      get { return _turns; }
      set { _turns = value; }
    }
    private uint _MaxScore = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"MaxScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint MaxScore
    {
      get { return _MaxScore; }
      set { _MaxScore = value; }
    }
    private uint _icon = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"icon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint icon
    {
      get { return _icon; }
      set { _icon = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TileRankReq")]
  public partial class TileRankReq : global::ProtoBuf.IExtensible
  {
    public TileRankReq() {}
    
    private uint _tile_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tile_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint tile_id
    {
      get { return _tile_id; }
      set { _tile_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TileRankResp")]
  public partial class TileRankResp : global::ProtoBuf.IExtensible
  {
    public TileRankResp() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _tile_union_rank = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"tile_union_rank", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> tile_union_rank
    {
      get { return _tile_union_rank; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _tile_personal_rank = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(3, Name=@"tile_personal_rank", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> tile_personal_rank
    {
      get { return _tile_personal_rank; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnterServerAndAwardReq")]
  public partial class EnterServerAndAwardReq : global::ProtoBuf.IExtensible
  {
    public EnterServerAndAwardReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnterServerAndAwardResp")]
  public partial class EnterServerAndAwardResp : global::ProtoBuf.IExtensible
  {
    public EnterServerAndAwardResp() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private uint _server_state = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"server_state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint server_state
    {
      get { return _server_state; }
      set { _server_state = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _server_name = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(3, Name=@"server_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> server_name
    {
      get { return _server_name; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuyCDClearReq")]
  public partial class BuyCDClearReq : global::ProtoBuf.IExtensible
  {
    public BuyCDClearReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuyCDClearResp")]
  public partial class BuyCDClearResp : global::ProtoBuf.IExtensible
  {
    public BuyCDClearResp() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private fogs.proto.msg.ItemInfo _buyItem = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"buyItem", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.ItemInfo buyItem
    {
      get { return _buyItem; }
      set { _buyItem = value; }
    }
    private uint _buy_times = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"buy_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint buy_times
    {
      get { return _buy_times; }
      set { _buy_times = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GotoBattleReq")]
  public partial class GotoBattleReq : global::ProtoBuf.IExtensible
  {
    public GotoBattleReq() {}
    
    private uint _tile_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tile_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint tile_id
    {
      get { return _tile_id; }
      set { _tile_id = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.SoldierList> _soldiers = new global::System.Collections.Generic.List<fogs.proto.msg.SoldierList>();
    [global::ProtoBuf.ProtoMember(2, Name=@"soldiers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.SoldierList> soldiers
    {
      get { return _soldiers; }
    }
  
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.EquipList> _equips = new global::System.Collections.Generic.List<fogs.proto.msg.EquipList>();
    [global::ProtoBuf.ProtoMember(3, Name=@"equips", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.EquipList> equips
    {
      get { return _equips; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GotoBattleResp")]
  public partial class GotoBattleResp : global::ProtoBuf.IExtensible
  {
    public GotoBattleResp() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private fogs.proto.msg.Attribute _hero_attribute = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"hero_attribute", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.Attribute hero_attribute
    {
      get { return _hero_attribute; }
      set { _hero_attribute = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CombatSettlementReq")]
  public partial class CombatSettlementReq : global::ProtoBuf.IExtensible
  {
    public CombatSettlementReq() {}
    
    private uint _accid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"accid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint accid
    {
      get { return _accid; }
      set { _accid = value; }
    }
    private uint _hurt = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"hurt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint hurt
    {
      get { return _hurt; }
      set { _hurt = value; }
    }
    private uint _tile_id = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"tile_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint tile_id
    {
      get { return _tile_id; }
      set { _tile_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CombatSettlementResp")]
  public partial class CombatSettlementResp : global::ProtoBuf.IExtensible
  {
    public CombatSettlementResp() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private fogs.proto.msg.ItemInfo _gains = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"gains", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.ItemInfo gains
    {
      get { return _gains; }
      set { _gains = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}