//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: DBInfo.proto
namespace fogs.proto.msg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ConnTimeInfo")]
  public partial class ConnTimeInfo : global::ProtoBuf.IExtensible
  {
    public ConnTimeInfo() {}
    
    private int _readtimeout = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"readtimeout", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int readtimeout
    {
      get { return _readtimeout; }
      set { _readtimeout = value; }
    }
    private int _writetimeout = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"writetimeout", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int writetimeout
    {
      get { return _writetimeout; }
      set { _writetimeout = value; }
    }
    private int _conntimeout = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"conntimeout", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int conntimeout
    {
      get { return _conntimeout; }
      set { _conntimeout = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DBInfo")]
  public partial class DBInfo : global::ProtoBuf.IExtensible
  {
    public DBInfo() {}
    
    private string _name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _ip = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ip
    {
      get { return _ip; }
      set { _ip = value; }
    }
    private int _port = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int port
    {
      get { return _port; }
      set { _port = value; }
    }
    private string _user = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"user", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string user
    {
      get { return _user; }
      set { _user = value; }
    }
    private string _pwd = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"pwd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string pwd
    {
      get { return _pwd; }
      set { _pwd = value; }
    }
    private fogs.proto.msg.ConnTimeInfo _conn_info = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"conn_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.ConnTimeInfo conn_info
    {
      get { return _conn_info; }
      set { _conn_info = value; }
    }
    private uint _area_id = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"area_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint area_id
    {
      get { return _area_id; }
      set { _area_id = value; }
    }
    private uint _conn_num = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"conn_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint conn_num
    {
      get { return _conn_num; }
      set { _conn_num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CharnameInfo")]
  public partial class CharnameInfo : global::ProtoBuf.IExtensible
  {
    public CharnameInfo() {}
    
    private string _charname = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"charname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string charname
    {
      get { return _charname; }
      set { _charname = value; }
    }
    private uint _state = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint state
    {
      get { return _state; }
      set { _state = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}