//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Expedition.proto
// Note: requires additional types generated from: Base.proto
// Note: requires additional types generated from: Castle.proto
namespace fogs.proto.msg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MatchEnemyReq")]
  public partial class MatchEnemyReq : global::ProtoBuf.IExtensible
  {
    public MatchEnemyReq() {}
    
    private int _type = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MatchEnemyResp")]
  public partial class MatchEnemyResp : global::ProtoBuf.IExtensible
  {
    public MatchEnemyResp() {}
    
    private uint _result = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int _type = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private fogs.proto.msg.ExpeditionInfo _expdt_info = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"expdt_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.ExpeditionInfo expdt_info
    {
      get { return _expdt_info; }
      set { _expdt_info = value; }
    }
    private int _max_times = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"max_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int max_times
    {
      get { return _max_times; }
      set { _max_times = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StartExpeditionReq")]
  public partial class StartExpeditionReq : global::ProtoBuf.IExtensible
  {
    public StartExpeditionReq() {}
    
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.SoldierList> _army = new global::System.Collections.Generic.List<fogs.proto.msg.SoldierList>();
    [global::ProtoBuf.ProtoMember(3, Name=@"army", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.SoldierList> army
    {
      get { return _army; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StartExpeditionResp")]
  public partial class StartExpeditionResp : global::ProtoBuf.IExtensible
  {
    public StartExpeditionResp() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ExpeditionResultReq")]
  public partial class ExpeditionResultReq : global::ProtoBuf.IExtensible
  {
    public ExpeditionResultReq() {}
    
    private int _exp_res = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"exp_res", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int exp_res
    {
      get { return _exp_res; }
      set { _exp_res = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.SoldierList> _dead_soldiers = new global::System.Collections.Generic.List<fogs.proto.msg.SoldierList>();
    [global::ProtoBuf.ProtoMember(2, Name=@"dead_soldiers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.SoldierList> dead_soldiers
    {
      get { return _dead_soldiers; }
    }
  
    private fogs.proto.msg.ArenaPlayer _remain_enemies = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"remain_enemies", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.ArenaPlayer remain_enemies
    {
      get { return _remain_enemies; }
      set { _remain_enemies = value; }
    }
    private uint _surplus_hp = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"surplus_hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint surplus_hp
    {
      get { return _surplus_hp; }
      set { _surplus_hp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ExpeditionResultResp")]
  public partial class ExpeditionResultResp : global::ProtoBuf.IExtensible
  {
    public ExpeditionResultResp() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int _exp_res = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"exp_res", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int exp_res
    {
      get { return _exp_res; }
      set { _exp_res = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.SoldierList> _dead_soldiers = new global::System.Collections.Generic.List<fogs.proto.msg.SoldierList>();
    [global::ProtoBuf.ProtoMember(3, Name=@"dead_soldiers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.SoldierList> dead_soldiers
    {
      get { return _dead_soldiers; }
    }
  
    private uint _surplus_hp = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"surplus_hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint surplus_hp
    {
      get { return _surplus_hp; }
      set { _surplus_hp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ExpeditionRewardReq")]
  public partial class ExpeditionRewardReq : global::ProtoBuf.IExtensible
  {
    public ExpeditionRewardReq() {}
    
    private uint _gate_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"gate_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint gate_id
    {
      get { return _gate_id; }
      set { _gate_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ExpeditionRewardResp")]
  public partial class ExpeditionRewardResp : global::ProtoBuf.IExtensible
  {
    public ExpeditionRewardResp() {}
    
    private uint _result = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private uint _gate_id = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"gate_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint gate_id
    {
      get { return _gate_id; }
      set { _gate_id = value; }
    }
    private fogs.proto.msg.DropList _drop_item = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"drop_item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.DropList drop_item
    {
      get { return _drop_item; }
      set { _drop_item = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}