//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Friends.proto
// Note: requires additional types generated from: Base.proto
// Note: requires additional types generated from: Task.proto
// Note: requires additional types generated from: Setting.proto
namespace fogs.proto.msg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BasePlayerInfo")]
  public partial class BasePlayerInfo : global::ProtoBuf.IExtensible
  {
    public BasePlayerInfo() {}
    
    private uint _accid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"accid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint accid
    {
      get { return _accid; }
      set { _accid = value; }
    }
    private uint _charid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"charid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charid
    {
      get { return _charid; }
      set { _charid = value; }
    }
    private string _accname = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"accname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string accname
    {
      get { return _accname; }
      set { _accname = value; }
    }
    private string _charname = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"charname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string charname
    {
      get { return _charname; }
      set { _charname = value; }
    }
    private uint _icon = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"icon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint icon
    {
      get { return _icon; }
      set { _icon = value; }
    }
    private uint _icon_frame = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"icon_frame", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint icon_frame
    {
      get { return _icon_frame; }
      set { _icon_frame = value; }
    }
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _union_id = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"union_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int union_id
    {
      get { return _union_id; }
      set { _union_id = value; }
    }
    private string _union_name = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"union_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string union_name
    {
      get { return _union_name; }
      set { _union_name = value; }
    }
    private int _combat_power = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"combat_power", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int combat_power
    {
      get { return _combat_power; }
      set { _combat_power = value; }
    }
    private int _enslave_status = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"enslave_status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int enslave_status
    {
      get { return _enslave_status; }
      set { _enslave_status = value; }
    }
    private uint _area_id = default(uint);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"area_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint area_id
    {
      get { return _area_id; }
      set { _area_id = value; }
    }
    private int _vip = default(int);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"vip", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int vip
    {
      get { return _vip; }
      set { _vip = value; }
    }
    private int _status = default(int);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private fogs.proto.msg.NotifySwitch _setting_switch = null;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"setting_switch", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.NotifySwitch setting_switch
    {
      get { return _setting_switch; }
      set { _setting_switch = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VerifiedInviteCode")]
  public partial class VerifiedInviteCode : global::ProtoBuf.IExtensible
  {
    public VerifiedInviteCode() {}
    
    private readonly global::System.Collections.Generic.List<string> _codes = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(1, Name=@"codes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> codes
    {
      get { return _codes; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AppendFriends")]
  public partial class AppendFriends : global::ProtoBuf.IExtensible
  {
    public AppendFriends() {}
    
    private int _tick = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tick", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int tick
    {
      get { return _tick; }
      set { _tick = value; }
    }
    private fogs.proto.msg.AppendFriendsStatus _status;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.AppendFriendsStatus status
    {
      get { return _status; }
      set { _status = value; }
    }
    private fogs.proto.msg.BasePlayerInfo _append_friends = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"append_friends", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.BasePlayerInfo append_friends
    {
      get { return _append_friends; }
      set { _append_friends = value; }
    }
    private int _op_tick = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"op_tick", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int op_tick
    {
      get { return _op_tick; }
      set { _op_tick = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TickAccid")]
  public partial class TickAccid : global::ProtoBuf.IExtensible
  {
    public TickAccid() {}
    
    private int _tick = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tick", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int tick
    {
      get { return _tick; }
      set { _tick = value; }
    }
    private uint _accid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"accid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint accid
    {
      get { return _accid; }
      set { _accid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FriendsInfo")]
  public partial class FriendsInfo : global::ProtoBuf.IExtensible
  {
    public FriendsInfo() {}
    
    private uint _recieve_ph_times = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"recieve_ph_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint recieve_ph_times
    {
      get { return _recieve_ph_times; }
      set { _recieve_ph_times = value; }
    }
    private uint _recieve_ph_tick = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"recieve_ph_tick", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint recieve_ph_tick
    {
      get { return _recieve_ph_tick; }
      set { _recieve_ph_tick = value; }
    }
    private uint _donate_ph_times = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"donate_ph_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint donate_ph_times
    {
      get { return _donate_ph_times; }
      set { _donate_ph_times = value; }
    }
    private uint _donate_ph_tick = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"donate_ph_tick", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint donate_ph_tick
    {
      get { return _donate_ph_tick; }
      set { _donate_ph_tick = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.BasePlayerInfo> _friends = new global::System.Collections.Generic.List<fogs.proto.msg.BasePlayerInfo>();
    [global::ProtoBuf.ProtoMember(5, Name=@"friends", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.BasePlayerInfo> friends
    {
      get { return _friends; }
    }
  
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.AppendFriends> _append_friends = new global::System.Collections.Generic.List<fogs.proto.msg.AppendFriends>();
    [global::ProtoBuf.ProtoMember(6, Name=@"append_friends", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.AppendFriends> append_friends
    {
      get { return _append_friends; }
    }
  
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.AppendFriends> _apply_friends = new global::System.Collections.Generic.List<fogs.proto.msg.AppendFriends>();
    [global::ProtoBuf.ProtoMember(7, Name=@"apply_friends", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.AppendFriends> apply_friends
    {
      get { return _apply_friends; }
    }
  
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.TickAccid> _donate_ph_info = new global::System.Collections.Generic.List<fogs.proto.msg.TickAccid>();
    [global::ProtoBuf.ProtoMember(8, Name=@"donate_ph_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.TickAccid> donate_ph_info
    {
      get { return _donate_ph_info; }
    }
  
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.TickAccid> _bedonate_ph_info = new global::System.Collections.Generic.List<fogs.proto.msg.TickAccid>();
    [global::ProtoBuf.ProtoMember(9, Name=@"bedonate_ph_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.TickAccid> bedonate_ph_info
    {
      get { return _bedonate_ph_info; }
    }
  
    private uint _refresh_tick = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"refresh_tick", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint refresh_tick
    {
      get { return _refresh_tick; }
      set { _refresh_tick = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ThirdFriendsInfo")]
  public partial class ThirdFriendsInfo : global::ProtoBuf.IExtensible
  {
    public ThirdFriendsInfo() {}
    
    private string _userid = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string userid
    {
      get { return _userid; }
      set { _userid = value; }
    }
    private uint _accid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"accid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint accid
    {
      get { return _accid; }
      set { _accid = value; }
    }
    private uint _invite_tick = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"invite_tick", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint invite_tick
    {
      get { return _invite_tick; }
      set { _invite_tick = value; }
    }
    private uint _wakeup_tick = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"wakeup_tick", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint wakeup_tick
    {
      get { return _wakeup_tick; }
      set { _wakeup_tick = value; }
    }
    private uint _recent_tick = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"recent_tick", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint recent_tick
    {
      get { return _recent_tick; }
      set { _recent_tick = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ThirdFriendsInfos")]
  public partial class ThirdFriendsInfos : global::ProtoBuf.IExtensible
  {
    public ThirdFriendsInfos() {}
    
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.ThirdFriendsInfo> _friends = new global::System.Collections.Generic.List<fogs.proto.msg.ThirdFriendsInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"friends", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.ThirdFriendsInfo> friends
    {
      get { return _friends; }
    }
  
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.TaskInfo> _tasks = new global::System.Collections.Generic.List<fogs.proto.msg.TaskInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"tasks", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.TaskInfo> tasks
    {
      get { return _tasks; }
    }
  
    private int _invite_nums = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"invite_nums", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int invite_nums
    {
      get { return _invite_nums; }
      set { _invite_nums = value; }
    }
    private int _wakeup_nums = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"wakeup_nums", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int wakeup_nums
    {
      get { return _wakeup_nums; }
      set { _wakeup_nums = value; }
    }
    private uint _reset_tick = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"reset_tick", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint reset_tick
    {
      get { return _reset_tick; }
      set { _reset_tick = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LineThirdFriendsInfos")]
  public partial class LineThirdFriendsInfos : global::ProtoBuf.IExtensible
  {
    public LineThirdFriendsInfos() {}
    
    private int _invite_nums = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"invite_nums", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int invite_nums
    {
      get { return _invite_nums; }
      set { _invite_nums = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.TaskInfo> _tasks = new global::System.Collections.Generic.List<fogs.proto.msg.TaskInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"tasks", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.TaskInfo> tasks
    {
      get { return _tasks; }
    }
  
    private uint _reset_tick = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"reset_tick", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint reset_tick
    {
      get { return _reset_tick; }
      set { _reset_tick = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ThirdFriends")]
  public partial class ThirdFriends : global::ProtoBuf.IExtensible
  {
    public ThirdFriends() {}
    
    private string _name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _login_tick = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"login_tick", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint login_tick
    {
      get { return _login_tick; }
      set { _login_tick = value; }
    }
    private uint _next_tick = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"next_tick", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint next_tick
    {
      get { return _next_tick; }
      set { _next_tick = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetThirdFriendsInfoReq")]
  public partial class GetThirdFriendsInfoReq : global::ProtoBuf.IExtensible
  {
    public GetThirdFriendsInfoReq() {}
    
    private fogs.proto.msg.ThirdFriendType _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.ThirdFriendType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _name = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> name
    {
      get { return _name; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetThirdFriendsInfoResp")]
  public partial class GetThirdFriendsInfoResp : global::ProtoBuf.IExtensible
  {
    public GetThirdFriendsInfoResp() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.ThirdFriends> _third_friends = new global::System.Collections.Generic.List<fogs.proto.msg.ThirdFriends>();
    [global::ProtoBuf.ProtoMember(2, Name=@"third_friends", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.ThirdFriends> third_friends
    {
      get { return _third_friends; }
    }
  
    private uint _wakeup_nums = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"wakeup_nums", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint wakeup_nums
    {
      get { return _wakeup_nums; }
      set { _wakeup_nums = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"InviteThirdFriendsReq")]
  public partial class InviteThirdFriendsReq : global::ProtoBuf.IExtensible
  {
    public InviteThirdFriendsReq() {}
    
    private fogs.proto.msg.ThirdFriendType _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.ThirdFriendType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private fogs.proto.msg.ThirdFriendsOpResultType _op_step;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"op_step", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.ThirdFriendsOpResultType op_step
    {
      get { return _op_step; }
      set { _op_step = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"InviteThirdFriendsResp")]
  public partial class InviteThirdFriendsResp : global::ProtoBuf.IExtensible
  {
    public InviteThirdFriendsResp() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private fogs.proto.msg.ThirdFriendType _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.ThirdFriendType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private fogs.proto.msg.ThirdFriendsOpResultType _op_step;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"op_step", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.ThirdFriendsOpResultType op_step
    {
      get { return _op_step; }
      set { _op_step = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.TaskInfo> _fb_invite_tasks = new global::System.Collections.Generic.List<fogs.proto.msg.TaskInfo>();
    [global::ProtoBuf.ProtoMember(5, Name=@"fb_invite_tasks", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.TaskInfo> fb_invite_tasks
    {
      get { return _fb_invite_tasks; }
    }
  
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.TaskInfo> _line_invite_tasks = new global::System.Collections.Generic.List<fogs.proto.msg.TaskInfo>();
    [global::ProtoBuf.ProtoMember(6, Name=@"line_invite_tasks", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.TaskInfo> line_invite_tasks
    {
      get { return _line_invite_tasks; }
    }
  
    private uint _next_tick = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"next_tick", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint next_tick
    {
      get { return _next_tick; }
      set { _next_tick = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WakeThirdFriendsReq")]
  public partial class WakeThirdFriendsReq : global::ProtoBuf.IExtensible
  {
    public WakeThirdFriendsReq() {}
    
    private fogs.proto.msg.ThirdFriendType _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.ThirdFriendType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private fogs.proto.msg.ThirdFriendsOpResultType _op_step;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"op_step", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.ThirdFriendsOpResultType op_step
    {
      get { return _op_step; }
      set { _op_step = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WakeThirdFriendsResp")]
  public partial class WakeThirdFriendsResp : global::ProtoBuf.IExtensible
  {
    public WakeThirdFriendsResp() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private fogs.proto.msg.ThirdFriendType _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.ThirdFriendType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private fogs.proto.msg.ThirdFriendsOpResultType _op_step;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"op_step", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.ThirdFriendsOpResultType op_step
    {
      get { return _op_step; }
      set { _op_step = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.TaskInfo> _fb_invite_tasks = new global::System.Collections.Generic.List<fogs.proto.msg.TaskInfo>();
    [global::ProtoBuf.ProtoMember(5, Name=@"fb_invite_tasks", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.TaskInfo> fb_invite_tasks
    {
      get { return _fb_invite_tasks; }
    }
  
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.TaskInfo> _line_invite_tasks = new global::System.Collections.Generic.List<fogs.proto.msg.TaskInfo>();
    [global::ProtoBuf.ProtoMember(6, Name=@"line_invite_tasks", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.TaskInfo> line_invite_tasks
    {
      get { return _line_invite_tasks; }
    }
  
    private fogs.proto.msg.DropList _awards_list = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"awards_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.DropList awards_list
    {
      get { return _awards_list; }
      set { _awards_list = value; }
    }
    private uint _reset_tick = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"reset_tick", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint reset_tick
    {
      get { return _reset_tick; }
      set { _reset_tick = value; }
    }
    private uint _wakeup_nums = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"wakeup_nums", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint wakeup_nums
    {
      get { return _wakeup_nums; }
      set { _wakeup_nums = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetThirdFriendsTaskReq")]
  public partial class GetThirdFriendsTaskReq : global::ProtoBuf.IExtensible
  {
    public GetThirdFriendsTaskReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetThirdFriendsTaskResp")]
  public partial class GetThirdFriendsTaskResp : global::ProtoBuf.IExtensible
  {
    public GetThirdFriendsTaskResp() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.TaskInfo> _fb_invite_tasks = new global::System.Collections.Generic.List<fogs.proto.msg.TaskInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"fb_invite_tasks", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.TaskInfo> fb_invite_tasks
    {
      get { return _fb_invite_tasks; }
    }
  
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.TaskInfo> _line_invite_tasks = new global::System.Collections.Generic.List<fogs.proto.msg.TaskInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"line_invite_tasks", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.TaskInfo> line_invite_tasks
    {
      get { return _line_invite_tasks; }
    }
  
    private int _fb_invite_nums = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"fb_invite_nums", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int fb_invite_nums
    {
      get { return _fb_invite_nums; }
      set { _fb_invite_nums = value; }
    }
    private int _line_invite_nums = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"line_invite_nums", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int line_invite_nums
    {
      get { return _line_invite_nums; }
      set { _line_invite_nums = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetThirdFriendsTaskAwardReq")]
  public partial class GetThirdFriendsTaskAwardReq : global::ProtoBuf.IExtensible
  {
    public GetThirdFriendsTaskAwardReq() {}
    
    private fogs.proto.msg.ThirdFriendType _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.ThirdFriendType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetThirdFriendsTaskAwardResp")]
  public partial class GetThirdFriendsTaskAwardResp : global::ProtoBuf.IExtensible
  {
    public GetThirdFriendsTaskAwardResp() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.TaskInfo> _task_list = new global::System.Collections.Generic.List<fogs.proto.msg.TaskInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"task_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.TaskInfo> task_list
    {
      get { return _task_list; }
    }
  
    private fogs.proto.msg.DropList _awards_list = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"awards_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.DropList awards_list
    {
      get { return _awards_list; }
      set { _awards_list = value; }
    }
    private fogs.proto.msg.ThirdFriendType _type;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.ThirdFriendType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _invite_nums = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"invite_nums", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int invite_nums
    {
      get { return _invite_nums; }
      set { _invite_nums = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ApplyAddFriendsReq")]
  public partial class ApplyAddFriendsReq : global::ProtoBuf.IExtensible
  {
    public ApplyAddFriendsReq() {}
    
    private string _accname = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"accname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string accname
    {
      get { return _accname; }
      set { _accname = value; }
    }
    private int _accid = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"accid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int accid
    {
      get { return _accid; }
      set { _accid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ApplyAddFriendsResp")]
  public partial class ApplyAddFriendsResp : global::ProtoBuf.IExtensible
  {
    public ApplyAddFriendsResp() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private string _accname = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"accname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string accname
    {
      get { return _accname; }
      set { _accname = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DonateFriendsHpReq")]
  public partial class DonateFriendsHpReq : global::ProtoBuf.IExtensible
  {
    public DonateFriendsHpReq() {}
    
    private fogs.proto.msg.FriendsOpType _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.FriendsOpType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _accid = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(2, Name=@"accid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> accid
    {
      get { return _accid; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DonateFriendsHpResp")]
  public partial class DonateFriendsHpResp : global::ProtoBuf.IExtensible
  {
    public DonateFriendsHpResp() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.TickAccid> _accid = new global::System.Collections.Generic.List<fogs.proto.msg.TickAccid>();
    [global::ProtoBuf.ProtoMember(2, Name=@"accid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.TickAccid> accid
    {
      get { return _accid; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RecieveFriendHpReq")]
  public partial class RecieveFriendHpReq : global::ProtoBuf.IExtensible
  {
    public RecieveFriendHpReq() {}
    
    private fogs.proto.msg.FriendsOpType _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.FriendsOpType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _accids = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(2, Name=@"accids", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> accids
    {
      get { return _accids; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RecieveFriendHpResp")]
  public partial class RecieveFriendHpResp : global::ProtoBuf.IExtensible
  {
    public RecieveFriendHpResp() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private fogs.proto.msg.FriendsOpType _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.FriendsOpType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.TickAccid> _accids = new global::System.Collections.Generic.List<fogs.proto.msg.TickAccid>();
    [global::ProtoBuf.ProtoMember(3, Name=@"accids", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.TickAccid> accids
    {
      get { return _accids; }
    }
  
    private int _ph_power = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"ph_power", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ph_power
    {
      get { return _ph_power; }
      set { _ph_power = value; }
    }
    private int _recieve_ph_power = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"recieve_ph_power", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int recieve_ph_power
    {
      get { return _recieve_ph_power; }
      set { _recieve_ph_power = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetFriendsListReq")]
  public partial class GetFriendsListReq : global::ProtoBuf.IExtensible
  {
    public GetFriendsListReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetFriendsListResp")]
  public partial class GetFriendsListResp : global::ProtoBuf.IExtensible
  {
    public GetFriendsListResp() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private fogs.proto.msg.FriendsInfo _friends_info = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"friends_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.FriendsInfo friends_info
    {
      get { return _friends_info; }
      set { _friends_info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetAppendFriendsListReq")]
  public partial class GetAppendFriendsListReq : global::ProtoBuf.IExtensible
  {
    public GetAppendFriendsListReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetAppendFriendsListResp")]
  public partial class GetAppendFriendsListResp : global::ProtoBuf.IExtensible
  {
    public GetAppendFriendsListResp() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.AppendFriends> _append_list = new global::System.Collections.Generic.List<fogs.proto.msg.AppendFriends>();
    [global::ProtoBuf.ProtoMember(2, Name=@"append_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.AppendFriends> append_list
    {
      get { return _append_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AccnameToAccid")]
  public partial class AccnameToAccid : global::ProtoBuf.IExtensible
  {
    public AccnameToAccid() {}
    
    private uint _accid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"accid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint accid
    {
      get { return _accid; }
      set { _accid = value; }
    }
    private string _accname = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"accname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string accname
    {
      get { return _accname; }
      set { _accname = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AuditAppendFriendsReq")]
  public partial class AuditAppendFriendsReq : global::ProtoBuf.IExtensible
  {
    public AuditAppendFriendsReq() {}
    
    private fogs.proto.msg.AuditFriendsOpType _op_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"op_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.AuditFriendsOpType op_type
    {
      get { return _op_type; }
      set { _op_type = value; }
    }
    private fogs.proto.msg.FriendsOpType _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.FriendsOpType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.AccnameToAccid> _accname_accids = new global::System.Collections.Generic.List<fogs.proto.msg.AccnameToAccid>();
    [global::ProtoBuf.ProtoMember(3, Name=@"accname_accids", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.AccnameToAccid> accname_accids
    {
      get { return _accname_accids; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AuditAppendFriendsResp")]
  public partial class AuditAppendFriendsResp : global::ProtoBuf.IExtensible
  {
    public AuditAppendFriendsResp() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private fogs.proto.msg.AuditFriendsOpType _op_type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"op_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.AuditFriendsOpType op_type
    {
      get { return _op_type; }
      set { _op_type = value; }
    }
    private fogs.proto.msg.FriendsOpType _type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.FriendsOpType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.AppendFriends> _append_friends = new global::System.Collections.Generic.List<fogs.proto.msg.AppendFriends>();
    [global::ProtoBuf.ProtoMember(4, Name=@"append_friends", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.AppendFriends> append_friends
    {
      get { return _append_friends; }
    }
  
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.BasePlayerInfo> _friends = new global::System.Collections.Generic.List<fogs.proto.msg.BasePlayerInfo>();
    [global::ProtoBuf.ProtoMember(5, Name=@"friends", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.BasePlayerInfo> friends
    {
      get { return _friends; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SearchFriendsReq")]
  public partial class SearchFriendsReq : global::ProtoBuf.IExtensible
  {
    public SearchFriendsReq() {}
    
    private string _charname = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"charname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string charname
    {
      get { return _charname; }
      set { _charname = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SearchFriendsResp")]
  public partial class SearchFriendsResp : global::ProtoBuf.IExtensible
  {
    public SearchFriendsResp() {}
    
    private uint _result = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private fogs.proto.msg.BasePlayerInfo _friend = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"friend", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.BasePlayerInfo friend
    {
      get { return _friend; }
      set { _friend = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DelFriendsReq")]
  public partial class DelFriendsReq : global::ProtoBuf.IExtensible
  {
    public DelFriendsReq() {}
    
    private uint _accid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"accid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint accid
    {
      get { return _accid; }
      set { _accid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DelFriendsResp")]
  public partial class DelFriendsResp : global::ProtoBuf.IExtensible
  {
    public DelFriendsResp() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private fogs.proto.msg.BasePlayerInfo _friend = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"friend", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.BasePlayerInfo friend
    {
      get { return _friend; }
      set { _friend = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RefreshRecommendFriendsReq")]
  public partial class RefreshRecommendFriendsReq : global::ProtoBuf.IExtensible
  {
    public RefreshRecommendFriendsReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RefreshRecommendFriendsResp")]
  public partial class RefreshRecommendFriendsResp : global::ProtoBuf.IExtensible
  {
    public RefreshRecommendFriendsResp() {}
    
    private uint _result = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.BasePlayerInfo> _re_friends = new global::System.Collections.Generic.List<fogs.proto.msg.BasePlayerInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"re_friends", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.BasePlayerInfo> re_friends
    {
      get { return _re_friends; }
    }
  
    private uint _refresh_tick = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"refresh_tick", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint refresh_tick
    {
      get { return _refresh_tick; }
      set { _refresh_tick = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetTopPlayerInfoReq")]
  public partial class GetTopPlayerInfoReq : global::ProtoBuf.IExtensible
  {
    public GetTopPlayerInfoReq() {}
    
    private uint _accid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"accid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint accid
    {
      get { return _accid; }
      set { _accid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetTopPlayerInfoResp")]
  public partial class GetTopPlayerInfoResp : global::ProtoBuf.IExtensible
  {
    public GetTopPlayerInfoResp() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private fogs.proto.msg.ArenaPlayer _player_info = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"player_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.ArenaPlayer player_info
    {
      get { return _player_info; }
      set { _player_info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VerifyInviteCodeReq")]
  public partial class VerifyInviteCodeReq : global::ProtoBuf.IExtensible
  {
    public VerifyInviteCodeReq() {}
    
    private string _code = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string code
    {
      get { return _code; }
      set { _code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VerifyInviteCodeResp")]
  public partial class VerifyInviteCodeResp : global::ProtoBuf.IExtensible
  {
    public VerifyInviteCodeResp() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int _invite_nums = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"invite_nums", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int invite_nums
    {
      get { return _invite_nums; }
      set { _invite_nums = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.TaskInfo> _task_list = new global::System.Collections.Generic.List<fogs.proto.msg.TaskInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"task_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.TaskInfo> task_list
    {
      get { return _task_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetInviteCodeTaskListReq")]
  public partial class GetInviteCodeTaskListReq : global::ProtoBuf.IExtensible
  {
    public GetInviteCodeTaskListReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetInviteCodeTaskListResp")]
  public partial class GetInviteCodeTaskListResp : global::ProtoBuf.IExtensible
  {
    public GetInviteCodeTaskListResp() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.TaskInfo> _task_list = new global::System.Collections.Generic.List<fogs.proto.msg.TaskInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"task_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.TaskInfo> task_list
    {
      get { return _task_list; }
    }
  
    private int _invite_num = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"invite_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int invite_num
    {
      get { return _invite_num; }
      set { _invite_num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetInviteCodeTaskAwardReq")]
  public partial class GetInviteCodeTaskAwardReq : global::ProtoBuf.IExtensible
  {
    public GetInviteCodeTaskAwardReq() {}
    
    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetInviteCodeTaskAwardResp")]
  public partial class GetInviteCodeTaskAwardResp : global::ProtoBuf.IExtensible
  {
    public GetInviteCodeTaskAwardResp() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.TaskInfo> _task_list = new global::System.Collections.Generic.List<fogs.proto.msg.TaskInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"task_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.TaskInfo> task_list
    {
      get { return _task_list; }
    }
  
    private fogs.proto.msg.DropList _awards_list = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"awards_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.DropList awards_list
    {
      get { return _awards_list; }
      set { _awards_list = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"AppendFriendsStatus")]
    public enum AppendFriendsStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"AFS_UNDO", Value=1)]
      AFS_UNDO = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AFS_ACCPETED", Value=2)]
      AFS_ACCPETED = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AFS_REFUSED", Value=3)]
      AFS_REFUSED = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ThirdFriendType")]
    public enum ThirdFriendType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FACEBOOK", Value=1)]
      FACEBOOK = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LINE", Value=2)]
      LINE = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ThirdFriendsOpResultType")]
    public enum ThirdFriendsOpResultType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAKE_SUCCESS", Value=1)]
      FAKE_SUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=2)]
      SUCCESS = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"FriendsOpType")]
    public enum FriendsOpType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FO_ONE", Value=1)]
      FO_ONE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FO_ALL", Value=2)]
      FO_ALL = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"AuditFriendsOpType")]
    public enum AuditFriendsOpType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"AFO_ACCPET", Value=1)]
      AFO_ACCPET = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AFO_REFUSE", Value=2)]
      AFO_REFUSE = 2
    }
  
}