//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Log.proto
namespace fogs.proto.msg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LogData")]
  public partial class LogData : global::ProtoBuf.IExtensible
  {
    public LogData() {}
    
    private fogs.proto.msg.NewPlayerLog _new_player = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"new_player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.NewPlayerLog new_player
    {
      get { return _new_player; }
      set { _new_player = value; }
    }
    private fogs.proto.msg.LoginQuitLog _login_quit = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"login_quit", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.LoginQuitLog login_quit
    {
      get { return _login_quit; }
      set { _login_quit = value; }
    }
    private fogs.proto.msg.SuggestLog _suggest = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"suggest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.SuggestLog suggest
    {
      get { return _suggest; }
      set { _suggest = value; }
    }
    private fogs.proto.msg.MoneyGetLog _money_get = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"money_get", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.MoneyGetLog money_get
    {
      get { return _money_get; }
      set { _money_get = value; }
    }
    private fogs.proto.msg.MoneyUseLog _money_use = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"money_use", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.MoneyUseLog money_use
    {
      get { return _money_use; }
      set { _money_use = value; }
    }
    private fogs.proto.msg.EquipGetLog _equip_get = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"equip_get", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.EquipGetLog equip_get
    {
      get { return _equip_get; }
      set { _equip_get = value; }
    }
    private fogs.proto.msg.PropGetLog _prop_get = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"prop_get", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.PropGetLog prop_get
    {
      get { return _prop_get; }
      set { _prop_get = value; }
    }
    private fogs.proto.msg.FirstRechargeLog _first_recharge = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"first_recharge", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.FirstRechargeLog first_recharge
    {
      get { return _first_recharge; }
      set { _first_recharge = value; }
    }
    private fogs.proto.msg.RechargeLog _recharge = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"recharge", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.RechargeLog recharge
    {
      get { return _recharge; }
      set { _recharge = value; }
    }
    private fogs.proto.msg.PropUseLog _prop_use = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"prop_use", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.PropUseLog prop_use
    {
      get { return _prop_use; }
      set { _prop_use = value; }
    }
    private fogs.proto.msg.PlayerUpLvLog _player_up_lv = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"player_up_lv", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.PlayerUpLvLog player_up_lv
    {
      get { return _player_up_lv; }
      set { _player_up_lv = value; }
    }
    private fogs.proto.msg.OnlinePlayerLog _online_player = null;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"online_player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.OnlinePlayerLog online_player
    {
      get { return _online_player; }
      set { _online_player = value; }
    }
    private fogs.proto.msg.OpenServerLog _open_server = null;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"open_server", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.OpenServerLog open_server
    {
      get { return _open_server; }
      set { _open_server = value; }
    }
    private fogs.proto.msg.ActivityLog _activity = null;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"activity", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.ActivityLog activity
    {
      get { return _activity; }
      set { _activity = value; }
    }
    private fogs.proto.msg.ShopBuyLog _shop_buy = null;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"shop_buy", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.ShopBuyLog shop_buy
    {
      get { return _shop_buy; }
      set { _shop_buy = value; }
    }
    private fogs.proto.msg.SoldierLog _soldier_get = null;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"soldier_get", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.SoldierLog soldier_get
    {
      get { return _soldier_get; }
      set { _soldier_get = value; }
    }
    private fogs.proto.msg.SoldierLog _soldier_use = null;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"soldier_use", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.SoldierLog soldier_use
    {
      get { return _soldier_use; }
      set { _soldier_use = value; }
    }
    private fogs.proto.msg.DungeonLog _dungeon_log = null;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"dungeon_log", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.DungeonLog dungeon_log
    {
      get { return _dungeon_log; }
      set { _dungeon_log = value; }
    }
    private fogs.proto.msg.GuideLog _guide_log = null;
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"guide_log", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.GuideLog guide_log
    {
      get { return _guide_log; }
      set { _guide_log = value; }
    }
    private fogs.proto.msg.UpVipLvLog _up_vip_log = null;
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"up_vip_log", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.UpVipLvLog up_vip_log
    {
      get { return _up_vip_log; }
      set { _up_vip_log = value; }
    }
    private fogs.proto.msg.DeviceLog _device_log = null;
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"device_log", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.DeviceLog device_log
    {
      get { return _device_log; }
      set { _device_log = value; }
    }
    private fogs.proto.msg.LoginLog _login_log = null;
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"login_log", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.LoginLog login_log
    {
      get { return _login_log; }
      set { _login_log = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LogInfoReq")]
  public partial class LogInfoReq : global::ProtoBuf.IExtensible
  {
    public LogInfoReq() {}
    
    private uint _log_type = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"log_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint log_type
    {
      get { return _log_type; }
      set { _log_type = value; }
    }
    private fogs.proto.msg.LogData _log_data = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"log_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.LogData log_data
    {
      get { return _log_data; }
      set { _log_data = value; }
    }
    private uint _log_area_id = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"log_area_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint log_area_id
    {
      get { return _log_area_id; }
      set { _log_area_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LogInfoResp")]
  public partial class LogInfoResp : global::ProtoBuf.IExtensible
  {
    public LogInfoResp() {}
    
    private uint _log_type = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"log_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint log_type
    {
      get { return _log_type; }
      set { _log_type = value; }
    }
    private uint _result = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NewPlayerLog")]
  public partial class NewPlayerLog : global::ProtoBuf.IExtensible
  {
    public NewPlayerLog() {}
    
    private uint _accid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"accid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint accid
    {
      get { return _accid; }
      set { _accid = value; }
    }
    private uint _sdk_type = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"sdk_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sdk_type
    {
      get { return _sdk_type; }
      set { _sdk_type = value; }
    }
    private uint _time = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint time
    {
      get { return _time; }
      set { _time = value; }
    }
    private uint _area_id = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"area_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint area_id
    {
      get { return _area_id; }
      set { _area_id = value; }
    }
    private string _accname = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"accname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string accname
    {
      get { return _accname; }
      set { _accname = value; }
    }
    private string _charname = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"charname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string charname
    {
      get { return _charname; }
      set { _charname = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginQuitLog")]
  public partial class LoginQuitLog : global::ProtoBuf.IExtensible
  {
    public LoginQuitLog() {}
    
    private uint _accid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"accid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint accid
    {
      get { return _accid; }
      set { _accid = value; }
    }
    private uint _sdk_type = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"sdk_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sdk_type
    {
      get { return _sdk_type; }
      set { _sdk_type = value; }
    }
    private uint _time_login = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"time_login", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint time_login
    {
      get { return _time_login; }
      set { _time_login = value; }
    }
    private uint _time_quit = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"time_quit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint time_quit
    {
      get { return _time_quit; }
      set { _time_quit = value; }
    }
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _area_id = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"area_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint area_id
    {
      get { return _area_id; }
      set { _area_id = value; }
    }
    private string _accname = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"accname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string accname
    {
      get { return _accname; }
      set { _accname = value; }
    }
    private string _device_id = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"device_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string device_id
    {
      get { return _device_id; }
      set { _device_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SuggestLog")]
  public partial class SuggestLog : global::ProtoBuf.IExtensible
  {
    public SuggestLog() {}
    
    private uint _accid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"accid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint accid
    {
      get { return _accid; }
      set { _accid = value; }
    }
    private string _title = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"title", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string title
    {
      get { return _title; }
      set { _title = value; }
    }
    private string _content = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string content
    {
      get { return _content; }
      set { _content = value; }
    }
    private string _time = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string time
    {
      get { return _time; }
      set { _time = value; }
    }
    private string _player_name = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"player_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string player_name
    {
      get { return _player_name; }
      set { _player_name = value; }
    }
    private uint _type = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _status = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint status
    {
      get { return _status; }
      set { _status = value; }
    }
    private uint _area_id = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"area_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint area_id
    {
      get { return _area_id; }
      set { _area_id = value; }
    }
    private string _accname = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"accname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string accname
    {
      get { return _accname; }
      set { _accname = value; }
    }
    private uint _sdk_type = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"sdk_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sdk_type
    {
      get { return _sdk_type; }
      set { _sdk_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MoneyGetLog")]
  public partial class MoneyGetLog : global::ProtoBuf.IExtensible
  {
    public MoneyGetLog() {}
    
    private uint _accid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"accid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint accid
    {
      get { return _accid; }
      set { _accid = value; }
    }
    private uint _sdk_type = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"sdk_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sdk_type
    {
      get { return _sdk_type; }
      set { _sdk_type = value; }
    }
    private uint _area_id = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"area_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint area_id
    {
      get { return _area_id; }
      set { _area_id = value; }
    }
    private uint _money_type = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"money_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint money_type
    {
      get { return _money_type; }
      set { _money_type = value; }
    }
    private uint _get_consume_way = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"get_consume_way", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint get_consume_way
    {
      get { return _get_consume_way; }
      set { _get_consume_way = value; }
    }
    private uint _time = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint time
    {
      get { return _time; }
      set { _time = value; }
    }
    private uint _money_num = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"money_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint money_num
    {
      get { return _money_num; }
      set { _money_num = value; }
    }
    private uint _get_all = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"get_all", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint get_all
    {
      get { return _get_all; }
      set { _get_all = value; }
    }
    private uint _now_num = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"now_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint now_num
    {
      get { return _now_num; }
      set { _now_num = value; }
    }
    private string _accname = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"accname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string accname
    {
      get { return _accname; }
      set { _accname = value; }
    }
    private string _commodity_id = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"commodity_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string commodity_id
    {
      get { return _commodity_id; }
      set { _commodity_id = value; }
    }
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MoneyUseLog")]
  public partial class MoneyUseLog : global::ProtoBuf.IExtensible
  {
    public MoneyUseLog() {}
    
    private uint _accid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"accid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint accid
    {
      get { return _accid; }
      set { _accid = value; }
    }
    private uint _sdk_type = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"sdk_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sdk_type
    {
      get { return _sdk_type; }
      set { _sdk_type = value; }
    }
    private uint _area_id = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"area_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint area_id
    {
      get { return _area_id; }
      set { _area_id = value; }
    }
    private uint _money_type = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"money_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint money_type
    {
      get { return _money_type; }
      set { _money_type = value; }
    }
    private uint _get_consume_way = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"get_consume_way", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint get_consume_way
    {
      get { return _get_consume_way; }
      set { _get_consume_way = value; }
    }
    private uint _time = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint time
    {
      get { return _time; }
      set { _time = value; }
    }
    private uint _money_num = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"money_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint money_num
    {
      get { return _money_num; }
      set { _money_num = value; }
    }
    private uint _get_all = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"get_all", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint get_all
    {
      get { return _get_all; }
      set { _get_all = value; }
    }
    private uint _now_num = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"now_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint now_num
    {
      get { return _now_num; }
      set { _now_num = value; }
    }
    private uint _commodity_id = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"commodity_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint commodity_id
    {
      get { return _commodity_id; }
      set { _commodity_id = value; }
    }
    private string _accname = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"accname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string accname
    {
      get { return _accname; }
      set { _accname = value; }
    }
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipGetLog")]
  public partial class EquipGetLog : global::ProtoBuf.IExtensible
  {
    public EquipGetLog() {}
    
    private uint _accid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"accid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint accid
    {
      get { return _accid; }
      set { _accid = value; }
    }
    private uint _sdk_type = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"sdk_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sdk_type
    {
      get { return _sdk_type; }
      set { _sdk_type = value; }
    }
    private uint _area_id = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"area_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint area_id
    {
      get { return _area_id; }
      set { _area_id = value; }
    }
    private uint _item_id = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"item_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint item_id
    {
      get { return _item_id; }
      set { _item_id = value; }
    }
    private uint _item_type = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"item_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint item_type
    {
      get { return _item_type; }
      set { _item_type = value; }
    }
    private uint _item_num = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"item_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint item_num
    {
      get { return _item_num; }
      set { _item_num = value; }
    }
    private uint _get_consume_way = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"get_consume_way", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint get_consume_way
    {
      get { return _get_consume_way; }
      set { _get_consume_way = value; }
    }
    private uint _time = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint time
    {
      get { return _time; }
      set { _time = value; }
    }
    private uint _now_num = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"now_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint now_num
    {
      get { return _now_num; }
      set { _now_num = value; }
    }
    private string _accname = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"accname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string accname
    {
      get { return _accname; }
      set { _accname = value; }
    }
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PropGetLog")]
  public partial class PropGetLog : global::ProtoBuf.IExtensible
  {
    public PropGetLog() {}
    
    private uint _accid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"accid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint accid
    {
      get { return _accid; }
      set { _accid = value; }
    }
    private uint _sdk_type = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"sdk_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sdk_type
    {
      get { return _sdk_type; }
      set { _sdk_type = value; }
    }
    private uint _area_id = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"area_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint area_id
    {
      get { return _area_id; }
      set { _area_id = value; }
    }
    private uint _item_id = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"item_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint item_id
    {
      get { return _item_id; }
      set { _item_id = value; }
    }
    private uint _item_type = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"item_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint item_type
    {
      get { return _item_type; }
      set { _item_type = value; }
    }
    private uint _item_num = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"item_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint item_num
    {
      get { return _item_num; }
      set { _item_num = value; }
    }
    private uint _get_consume_way = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"get_consume_way", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint get_consume_way
    {
      get { return _get_consume_way; }
      set { _get_consume_way = value; }
    }
    private uint _time = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint time
    {
      get { return _time; }
      set { _time = value; }
    }
    private uint _now_num = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"now_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint now_num
    {
      get { return _now_num; }
      set { _now_num = value; }
    }
    private string _accname = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"accname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string accname
    {
      get { return _accname; }
      set { _accname = value; }
    }
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PropUseLog")]
  public partial class PropUseLog : global::ProtoBuf.IExtensible
  {
    public PropUseLog() {}
    
    private uint _accid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"accid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint accid
    {
      get { return _accid; }
      set { _accid = value; }
    }
    private uint _sdk_type = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"sdk_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sdk_type
    {
      get { return _sdk_type; }
      set { _sdk_type = value; }
    }
    private uint _area_id = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"area_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint area_id
    {
      get { return _area_id; }
      set { _area_id = value; }
    }
    private uint _item_id = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"item_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint item_id
    {
      get { return _item_id; }
      set { _item_id = value; }
    }
    private uint _item_type = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"item_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint item_type
    {
      get { return _item_type; }
      set { _item_type = value; }
    }
    private uint _item_num = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"item_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint item_num
    {
      get { return _item_num; }
      set { _item_num = value; }
    }
    private uint _get_consume_way = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"get_consume_way", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint get_consume_way
    {
      get { return _get_consume_way; }
      set { _get_consume_way = value; }
    }
    private uint _time = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint time
    {
      get { return _time; }
      set { _time = value; }
    }
    private uint _now_num = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"now_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint now_num
    {
      get { return _now_num; }
      set { _now_num = value; }
    }
    private string _accname = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"accname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string accname
    {
      get { return _accname; }
      set { _accname = value; }
    }
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FirstRechargeLog")]
  public partial class FirstRechargeLog : global::ProtoBuf.IExtensible
  {
    public FirstRechargeLog() {}
    
    private uint _accid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"accid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint accid
    {
      get { return _accid; }
      set { _accid = value; }
    }
    private uint _sdk_type = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"sdk_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sdk_type
    {
      get { return _sdk_type; }
      set { _sdk_type = value; }
    }
    private uint _area_id = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"area_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint area_id
    {
      get { return _area_id; }
      set { _area_id = value; }
    }
    private uint _time = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint time
    {
      get { return _time; }
      set { _time = value; }
    }
    private uint _order_id = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"order_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint order_id
    {
      get { return _order_id; }
      set { _order_id = value; }
    }
    private uint _money = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint money
    {
      get { return _money; }
      set { _money = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RechargeLog")]
  public partial class RechargeLog : global::ProtoBuf.IExtensible
  {
    public RechargeLog() {}
    
    private uint _accid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"accid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint accid
    {
      get { return _accid; }
      set { _accid = value; }
    }
    private uint _sdk_type = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"sdk_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sdk_type
    {
      get { return _sdk_type; }
      set { _sdk_type = value; }
    }
    private uint _area_id = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"area_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint area_id
    {
      get { return _area_id; }
      set { _area_id = value; }
    }
    private uint _time = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint time
    {
      get { return _time; }
      set { _time = value; }
    }
    private string _order_id = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"order_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string order_id
    {
      get { return _order_id; }
      set { _order_id = value; }
    }
    private uint _money = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint money
    {
      get { return _money; }
      set { _money = value; }
    }
    private uint _vip_lv = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"vip_lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint vip_lv
    {
      get { return _vip_lv; }
      set { _vip_lv = value; }
    }
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _get_num = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"get_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint get_num
    {
      get { return _get_num; }
      set { _get_num = value; }
    }
    private uint _channel = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"channel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint channel
    {
      get { return _channel; }
      set { _channel = value; }
    }
    private uint _status = default(uint);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint status
    {
      get { return _status; }
      set { _status = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _accname = "";
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"accname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string accname
    {
      get { return _accname; }
      set { _accname = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerUpLvLog")]
  public partial class PlayerUpLvLog : global::ProtoBuf.IExtensible
  {
    public PlayerUpLvLog() {}
    
    private uint _accid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"accid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint accid
    {
      get { return _accid; }
      set { _accid = value; }
    }
    private uint _sdk_type = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"sdk_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sdk_type
    {
      get { return _sdk_type; }
      set { _sdk_type = value; }
    }
    private uint _area_id = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"area_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint area_id
    {
      get { return _area_id; }
      set { _area_id = value; }
    }
    private uint _time = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint time
    {
      get { return _time; }
      set { _time = value; }
    }
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _change_lv = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"change_lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint change_lv
    {
      get { return _change_lv; }
      set { _change_lv = value; }
    }
    private string _charname = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"charname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string charname
    {
      get { return _charname; }
      set { _charname = value; }
    }
    private string _accname = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"accname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string accname
    {
      get { return _accname; }
      set { _accname = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RegisterLogReq")]
  public partial class RegisterLogReq : global::ProtoBuf.IExtensible
  {
    public RegisterLogReq() {}
    
    private uint _accid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"accid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint accid
    {
      get { return _accid; }
      set { _accid = value; }
    }
    private uint _sdk_type = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"sdk_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sdk_type
    {
      get { return _sdk_type; }
      set { _sdk_type = value; }
    }
    private uint _time = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint time
    {
      get { return _time; }
      set { _time = value; }
    }
    private string _accname = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"accname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string accname
    {
      get { return _accname; }
      set { _accname = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OnlinePlayerLog")]
  public partial class OnlinePlayerLog : global::ProtoBuf.IExtensible
  {
    public OnlinePlayerLog() {}
    
    private uint _area_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"area_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint area_id
    {
      get { return _area_id; }
      set { _area_id = value; }
    }
    private uint _time = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint time
    {
      get { return _time; }
      set { _time = value; }
    }
    private uint _num = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint num
    {
      get { return _num; }
      set { _num = value; }
    }
    private string _sdk2num = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"sdk2num", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sdk2num
    {
      get { return _sdk2num; }
      set { _sdk2num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OpenServerLog")]
  public partial class OpenServerLog : global::ProtoBuf.IExtensible
  {
    public OpenServerLog() {}
    
    private uint _area_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"area_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint area_id
    {
      get { return _area_id; }
      set { _area_id = value; }
    }
    private uint _time = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint time
    {
      get { return _time; }
      set { _time = value; }
    }
    private uint _open_type = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"open_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint open_type
    {
      get { return _open_type; }
      set { _open_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ActivityLog")]
  public partial class ActivityLog : global::ProtoBuf.IExtensible
  {
    public ActivityLog() {}
    
    private uint _area_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"area_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint area_id
    {
      get { return _area_id; }
      set { _area_id = value; }
    }
    private uint _sdk_type = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"sdk_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sdk_type
    {
      get { return _sdk_type; }
      set { _sdk_type = value; }
    }
    private string _accname = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"accname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string accname
    {
      get { return _accname; }
      set { _accname = value; }
    }
    private uint _activity_id = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"activity_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint activity_id
    {
      get { return _activity_id; }
      set { _activity_id = value; }
    }
    private uint _accid = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"accid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint accid
    {
      get { return _accid; }
      set { _accid = value; }
    }
    private uint _condition = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"condition", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint condition
    {
      get { return _condition; }
      set { _condition = value; }
    }
    private uint _time = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint time
    {
      get { return _time; }
      set { _time = value; }
    }
    private uint _dropBagID = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"dropBagID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint dropBagID
    {
      get { return _dropBagID; }
      set { _dropBagID = value; }
    }
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ShopBuyLog")]
  public partial class ShopBuyLog : global::ProtoBuf.IExtensible
  {
    public ShopBuyLog() {}
    
    private uint _area_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"area_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint area_id
    {
      get { return _area_id; }
      set { _area_id = value; }
    }
    private uint _sdk_type = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"sdk_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sdk_type
    {
      get { return _sdk_type; }
      set { _sdk_type = value; }
    }
    private string _accname = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"accname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string accname
    {
      get { return _accname; }
      set { _accname = value; }
    }
    private uint _accid = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"accid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint accid
    {
      get { return _accid; }
      set { _accid = value; }
    }
    private uint _item_id = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"item_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint item_id
    {
      get { return _item_id; }
      set { _item_id = value; }
    }
    private uint _item_num = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"item_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint item_num
    {
      get { return _item_num; }
      set { _item_num = value; }
    }
    private uint _time = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint time
    {
      get { return _time; }
      set { _time = value; }
    }
    private uint _shop_type = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"shop_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint shop_type
    {
      get { return _shop_type; }
      set { _shop_type = value; }
    }
    private uint _money_type = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"money_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint money_type
    {
      get { return _money_type; }
      set { _money_type = value; }
    }
    private uint _money_num = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"money_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint money_num
    {
      get { return _money_num; }
      set { _money_num = value; }
    }
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoldierLog")]
  public partial class SoldierLog : global::ProtoBuf.IExtensible
  {
    public SoldierLog() {}
    
    private uint _accid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"accid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint accid
    {
      get { return _accid; }
      set { _accid = value; }
    }
    private uint _sdk_type = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"sdk_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sdk_type
    {
      get { return _sdk_type; }
      set { _sdk_type = value; }
    }
    private uint _area_id = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"area_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint area_id
    {
      get { return _area_id; }
      set { _area_id = value; }
    }
    private uint _soldier_id = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"soldier_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint soldier_id
    {
      get { return _soldier_id; }
      set { _soldier_id = value; }
    }
    private uint _soldier_num = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"soldier_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint soldier_num
    {
      get { return _soldier_num; }
      set { _soldier_num = value; }
    }
    private uint _time = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint time
    {
      get { return _time; }
      set { _time = value; }
    }
    private uint _get_consume_way = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"get_consume_way", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint get_consume_way
    {
      get { return _get_consume_way; }
      set { _get_consume_way = value; }
    }
    private string _accname = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"accname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string accname
    {
      get { return _accname; }
      set { _accname = value; }
    }
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _direct = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"direct", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint direct
    {
      get { return _direct; }
      set { _direct = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DungeonLog")]
  public partial class DungeonLog : global::ProtoBuf.IExtensible
  {
    public DungeonLog() {}
    
    private uint _area_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"area_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint area_id
    {
      get { return _area_id; }
      set { _area_id = value; }
    }
    private uint _accid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"accid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint accid
    {
      get { return _accid; }
      set { _accid = value; }
    }
    private uint _sdk_type = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"sdk_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sdk_type
    {
      get { return _sdk_type; }
      set { _sdk_type = value; }
    }
    private uint _time = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint time
    {
      get { return _time; }
      set { _time = value; }
    }
    private uint _dgn_id = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"dgn_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint dgn_id
    {
      get { return _dgn_id; }
      set { _dgn_id = value; }
    }
    private string _accname = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"accname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string accname
    {
      get { return _accname; }
      set { _accname = value; }
    }
    private uint _map_type = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"map_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint map_type
    {
      get { return _map_type; }
      set { _map_type = value; }
    }
    private uint _mode = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"mode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint mode
    {
      get { return _mode; }
      set { _mode = value; }
    }
    private uint _result = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GuideLog")]
  public partial class GuideLog : global::ProtoBuf.IExtensible
  {
    public GuideLog() {}
    
    private uint _area_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"area_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint area_id
    {
      get { return _area_id; }
      set { _area_id = value; }
    }
    private uint _accid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"accid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint accid
    {
      get { return _accid; }
      set { _accid = value; }
    }
    private uint _sdk_type = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"sdk_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sdk_type
    {
      get { return _sdk_type; }
      set { _sdk_type = value; }
    }
    private uint _time = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint time
    {
      get { return _time; }
      set { _time = value; }
    }
    private uint _guide_step = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"guide_step", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint guide_step
    {
      get { return _guide_step; }
      set { _guide_step = value; }
    }
    private string _accname = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"accname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string accname
    {
      get { return _accname; }
      set { _accname = value; }
    }
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpVipLvLog")]
  public partial class UpVipLvLog : global::ProtoBuf.IExtensible
  {
    public UpVipLvLog() {}
    
    private uint _area_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"area_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint area_id
    {
      get { return _area_id; }
      set { _area_id = value; }
    }
    private uint _accid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"accid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint accid
    {
      get { return _accid; }
      set { _accid = value; }
    }
    private uint _sdk_type = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"sdk_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sdk_type
    {
      get { return _sdk_type; }
      set { _sdk_type = value; }
    }
    private uint _time = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint time
    {
      get { return _time; }
      set { _time = value; }
    }
    private uint _vip_lv = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"vip_lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint vip_lv
    {
      get { return _vip_lv; }
      set { _vip_lv = value; }
    }
    private string _accname = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"accname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string accname
    {
      get { return _accname; }
      set { _accname = value; }
    }
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DeviceLog")]
  public partial class DeviceLog : global::ProtoBuf.IExtensible
  {
    public DeviceLog() {}
    
    private uint _area_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"area_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint area_id
    {
      get { return _area_id; }
      set { _area_id = value; }
    }
    private uint _accid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"accid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint accid
    {
      get { return _accid; }
      set { _accid = value; }
    }
    private uint _sdk_type = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"sdk_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sdk_type
    {
      get { return _sdk_type; }
      set { _sdk_type = value; }
    }
    private uint _time = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint time
    {
      get { return _time; }
      set { _time = value; }
    }
    private string _device_id = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"device_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string device_id
    {
      get { return _device_id; }
      set { _device_id = value; }
    }
    private string _accname = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"accname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string accname
    {
      get { return _accname; }
      set { _accname = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginLog")]
  public partial class LoginLog : global::ProtoBuf.IExtensible
  {
    public LoginLog() {}
    
    private uint _area_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"area_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint area_id
    {
      get { return _area_id; }
      set { _area_id = value; }
    }
    private uint _accid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"accid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint accid
    {
      get { return _accid; }
      set { _accid = value; }
    }
    private uint _sdk_type = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"sdk_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sdk_type
    {
      get { return _sdk_type; }
      set { _sdk_type = value; }
    }
    private string _accname = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"accname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string accname
    {
      get { return _accname; }
      set { _accname = value; }
    }
    private uint _time = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint time
    {
      get { return _time; }
      set { _time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"LogType")]
    public enum LogType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NEW_PLAYER", Value=1)]
      NEW_PLAYER = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_QUIT", Value=2)]
      LOGIN_QUIT = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUGGEST", Value=3)]
      SUGGEST = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MONEY_GET", Value=4)]
      MONEY_GET = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MONEY_USE", Value=5)]
      MONEY_USE = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EQUIP_GET", Value=6)]
      EQUIP_GET = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PROP_GET", Value=7)]
      PROP_GET = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIRST_RECHARGE", Value=8)]
      FIRST_RECHARGE = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RECHARGE", Value=9)]
      RECHARGE = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PROP_USE", Value=10)]
      PROP_USE = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PLAYER_UP_LV", Value=11)]
      PLAYER_UP_LV = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ONLINE_PLAYER", Value=12)]
      ONLINE_PLAYER = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPEN_SERVER", Value=13)]
      OPEN_SERVER = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACTIVITYLOG", Value=14)]
      ACTIVITYLOG = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SHOP_BUY_LOG", Value=15)]
      SHOP_BUY_LOG = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOLDIER_GET_LOG", Value=16)]
      SOLDIER_GET_LOG = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOLDIER_USE_LOG", Value=17)]
      SOLDIER_USE_LOG = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DUNGEON_LOG", Value=18)]
      DUNGEON_LOG = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GUIDE_LOG", Value=19)]
      GUIDE_LOG = 19,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UP_VIP_LV_LOG", Value=20)]
      UP_VIP_LV_LOG = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DEVICE_LOG", Value=21)]
      DEVICE_LOG = 21,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_LOG", Value=22)]
      LOGIN_LOG = 22
    }
  
}