//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Mail.proto
// Note: requires additional types generated from: Base.proto
// Note: requires additional types generated from: Friends.proto
namespace fogs.proto.msg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MailInfo")]
  public partial class MailInfo : global::ProtoBuf.IExtensible
  {
    public MailInfo() {}
    
    private ulong _mail_id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"mail_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong mail_id
    {
      get { return _mail_id; }
      set { _mail_id = value; }
    }
    private uint _type = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _status = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint status
    {
      get { return _status; }
      set { _status = value; }
    }
    private string _title = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"title", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string title
    {
      get { return _title; }
      set { _title = value; }
    }
    private string _body = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"body", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string body
    {
      get { return _body; }
      set { _body = value; }
    }
    private string _sentdate = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"sentdate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sentdate
    {
      get { return _sentdate; }
      set { _sentdate = value; }
    }
    private uint _deadline = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"deadline", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint deadline
    {
      get { return _deadline; }
      set { _deadline = value; }
    }
    private string _sender = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"sender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sender
    {
      get { return _sender; }
      set { _sender = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.Attachment> _attachments = new global::System.Collections.Generic.List<fogs.proto.msg.Attachment>();
    [global::ProtoBuf.ProtoMember(9, Name=@"attachments", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.Attachment> attachments
    {
      get { return _attachments; }
    }
  
    private fogs.proto.msg.ArenaRecord _record = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"record", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.ArenaRecord record
    {
      get { return _record; }
      set { _record = value; }
    }
    private fogs.proto.msg.ChatInfo _chat_info = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"chat_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.ChatInfo chat_info
    {
      get { return _chat_info; }
      set { _chat_info = value; }
    }
    private uint _kick_tick = default(uint);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"kick_tick", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint kick_tick
    {
      get { return _kick_tick; }
      set { _kick_tick = value; }
    }
    private uint _kick_union_id = default(uint);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"kick_union_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint kick_union_id
    {
      get { return _kick_union_id; }
      set { _kick_union_id = value; }
    }
    private string _back_other_info = "";
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"back_other_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string back_other_info
    {
      get { return _back_other_info; }
      set { _back_other_info = value; }
    }
    private fogs.proto.msg.AppendFriends _append_friends_info = null;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"append_friends_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.AppendFriends append_friends_info
    {
      get { return _append_friends_info; }
      set { _append_friends_info = value; }
    }
    private fogs.proto.msg.TickAccid _donate_friends_ph = null;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"donate_friends_ph", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.TickAccid donate_friends_ph
    {
      get { return _donate_friends_ph; }
      set { _donate_friends_ph = value; }
    }
    private uint _del_friend_accid = default(uint);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"del_friend_accid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint del_friend_accid
    {
      get { return _del_friend_accid; }
      set { _del_friend_accid = value; }
    }
    private fogs.proto.msg.ArenaRecord _pole_record = null;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"pole_record", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.ArenaRecord pole_record
    {
      get { return _pole_record; }
      set { _pole_record = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.LifeSoul> _return_souls = new global::System.Collections.Generic.List<fogs.proto.msg.LifeSoul>();
    [global::ProtoBuf.ProtoMember(19, Name=@"return_souls", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.LifeSoul> return_souls
    {
      get { return _return_souls; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DBMailInfo")]
  public partial class DBMailInfo : global::ProtoBuf.IExtensible
  {
    public DBMailInfo() {}
    
    private ulong _mail_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mail_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong mail_id
    {
      get { return _mail_id; }
      set { _mail_id = value; }
    }
    private uint _accid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"accid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint accid
    {
      get { return _accid; }
      set { _accid = value; }
    }
    private fogs.proto.msg.MailInfo _mail_info;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"mail_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public fogs.proto.msg.MailInfo mail_info
    {
      get { return _mail_info; }
      set { _mail_info = value; }
    }
    private fogs.proto.msg.PublicMailAccidList _accid_list;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"accid_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public fogs.proto.msg.PublicMailAccidList accid_list
    {
      get { return _accid_list; }
      set { _accid_list = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PublicMailAccidList")]
  public partial class PublicMailAccidList : global::ProtoBuf.IExtensible
  {
    public PublicMailAccidList() {}
    
    private readonly global::System.Collections.Generic.List<uint> _accid_list = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"accid_list", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> accid_list
    {
      get { return _accid_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetMailReq")]
  public partial class GetMailReq : global::ProtoBuf.IExtensible
  {
    public GetMailReq() {}
    
    private uint _page = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"page", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint page
    {
      get { return _page; }
      set { _page = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetMailResp")]
  public partial class GetMailResp : global::ProtoBuf.IExtensible
  {
    public GetMailResp() {}
    
    private uint _result = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.MailInfo> _mail_list = new global::System.Collections.Generic.List<fogs.proto.msg.MailInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"mail_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.MailInfo> mail_list
    {
      get { return _mail_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReadMailReq")]
  public partial class ReadMailReq : global::ProtoBuf.IExtensible
  {
    public ReadMailReq() {}
    
    private ulong _mail_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mail_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong mail_id
    {
      get { return _mail_id; }
      set { _mail_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReadMailResp")]
  public partial class ReadMailResp : global::ProtoBuf.IExtensible
  {
    public ReadMailResp() {}
    
    private uint _result = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private ulong _mail_id = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"mail_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong mail_id
    {
      get { return _mail_id; }
      set { _mail_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetMailAttReq")]
  public partial class GetMailAttReq : global::ProtoBuf.IExtensible
  {
    public GetMailAttReq() {}
    
    private ulong _mail_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mail_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong mail_id
    {
      get { return _mail_id; }
      set { _mail_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetMailAttResp")]
  public partial class GetMailAttResp : global::ProtoBuf.IExtensible
  {
    public GetMailAttResp() {}
    
    private uint _result = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private ulong _mail_id = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"mail_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong mail_id
    {
      get { return _mail_id; }
      set { _mail_id = value; }
    }
    private uint _mail_del = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"mail_del", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint mail_del
    {
      get { return _mail_del; }
      set { _mail_del = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.ItemInfo> _update_item = new global::System.Collections.Generic.List<fogs.proto.msg.ItemInfo>();
    [global::ProtoBuf.ProtoMember(4, Name=@"update_item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.ItemInfo> update_item
    {
      get { return _update_item; }
    }
  
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.Equip> _update_equip = new global::System.Collections.Generic.List<fogs.proto.msg.Equip>();
    [global::ProtoBuf.ProtoMember(5, Name=@"update_equip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.Equip> update_equip
    {
      get { return _update_equip; }
    }
  
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.Equip> _update_soldierequip = new global::System.Collections.Generic.List<fogs.proto.msg.Equip>();
    [global::ProtoBuf.ProtoMember(6, Name=@"update_soldierequip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.Equip> update_soldierequip
    {
      get { return _update_soldierequip; }
    }
  
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.Soldier> _update_sodier = new global::System.Collections.Generic.List<fogs.proto.msg.Soldier>();
    [global::ProtoBuf.ProtoMember(7, Name=@"update_sodier", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.Soldier> update_sodier
    {
      get { return _update_sodier; }
    }
  
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.LifeSoul> _update_soul = new global::System.Collections.Generic.List<fogs.proto.msg.LifeSoul>();
    [global::ProtoBuf.ProtoMember(8, Name=@"update_soul", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.LifeSoul> update_soul
    {
      get { return _update_soul; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DeleteMailReq")]
  public partial class DeleteMailReq : global::ProtoBuf.IExtensible
  {
    public DeleteMailReq() {}
    
    private ulong _mail_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mail_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong mail_id
    {
      get { return _mail_id; }
      set { _mail_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DeleteMailResp")]
  public partial class DeleteMailResp : global::ProtoBuf.IExtensible
  {
    public DeleteMailResp() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private ulong _mail_id = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"mail_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong mail_id
    {
      get { return _mail_id; }
      set { _mail_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OneKeyReadMailReq")]
  public partial class OneKeyReadMailReq : global::ProtoBuf.IExtensible
  {
    public OneKeyReadMailReq() {}
    
    private readonly global::System.Collections.Generic.List<ulong> _mail_id_list = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(1, Name=@"mail_id_list", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> mail_id_list
    {
      get { return _mail_id_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OneKeyReadMailResp")]
  public partial class OneKeyReadMailResp : global::ProtoBuf.IExtensible
  {
    public OneKeyReadMailResp() {}
    
    private uint _result = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private readonly global::System.Collections.Generic.List<ulong> _success_mail_idlist = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(2, Name=@"success_mail_idlist", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> success_mail_idlist
    {
      get { return _success_mail_idlist; }
    }
  
    private readonly global::System.Collections.Generic.List<ulong> _fail_mail_idlist = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(3, Name=@"fail_mail_idlist", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> fail_mail_idlist
    {
      get { return _fail_mail_idlist; }
    }
  
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.ItemInfo> _update_item = new global::System.Collections.Generic.List<fogs.proto.msg.ItemInfo>();
    [global::ProtoBuf.ProtoMember(4, Name=@"update_item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.ItemInfo> update_item
    {
      get { return _update_item; }
    }
  
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.Equip> _update_equip = new global::System.Collections.Generic.List<fogs.proto.msg.Equip>();
    [global::ProtoBuf.ProtoMember(5, Name=@"update_equip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.Equip> update_equip
    {
      get { return _update_equip; }
    }
  
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.Equip> _update_soldierequip = new global::System.Collections.Generic.List<fogs.proto.msg.Equip>();
    [global::ProtoBuf.ProtoMember(6, Name=@"update_soldierequip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.Equip> update_soldierequip
    {
      get { return _update_soldierequip; }
    }
  
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.Soldier> _update_soldier = new global::System.Collections.Generic.List<fogs.proto.msg.Soldier>();
    [global::ProtoBuf.ProtoMember(7, Name=@"update_soldier", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.Soldier> update_soldier
    {
      get { return _update_soldier; }
    }
  
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.LifeSoul> _update_soul = new global::System.Collections.Generic.List<fogs.proto.msg.LifeSoul>();
    [global::ProtoBuf.ProtoMember(8, Name=@"update_soul", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.LifeSoul> update_soul
    {
      get { return _update_soul; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ManagerSendMailReq")]
  public partial class ManagerSendMailReq : global::ProtoBuf.IExtensible
  {
    public ManagerSendMailReq() {}
    
    private uint _recv_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"recv_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint recv_id
    {
      get { return _recv_id; }
      set { _recv_id = value; }
    }
    private uint _recv_charid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"recv_charid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint recv_charid
    {
      get { return _recv_charid; }
      set { _recv_charid = value; }
    }
    private uint _type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _valid_hour = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"valid_hour", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint valid_hour
    {
      get { return _valid_hour; }
      set { _valid_hour = value; }
    }
    private string _deadline = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"deadline", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string deadline
    {
      get { return _deadline; }
      set { _deadline = value; }
    }
    private uint _gold = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private uint _diamond = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint diamond
    {
      get { return _diamond; }
      set { _diamond = value; }
    }
    private uint _exp = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private uint _energy = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"energy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint energy
    {
      get { return _energy; }
      set { _energy = value; }
    }
    private uint _honour = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"honour", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint honour
    {
      get { return _honour; }
      set { _honour = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.Attachment> _item_list = new global::System.Collections.Generic.List<fogs.proto.msg.Attachment>();
    [global::ProtoBuf.ProtoMember(11, Name=@"item_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.Attachment> item_list
    {
      get { return _item_list; }
    }
  
    private string _title;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"title", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string title
    {
      get { return _title; }
      set { _title = value; }
    }
    private string _body;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"body", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string body
    {
      get { return _body; }
      set { _body = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NewMailNotify")]
  public partial class NewMailNotify : global::ProtoBuf.IExtensible
  {
    public NewMailNotify() {}
    
    private uint _unread_num = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"unread_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint unread_num
    {
      get { return _unread_num; }
      set { _unread_num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"MailType")]
    public enum MailType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYSTEM_MAIL", Value=1)]
      SYSTEM_MAIL = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTICE_MAIL", Value=2)]
      NOTICE_MAIL = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PRIVATE_CHAT_MAIL", Value=3)]
      PRIVATE_CHAT_MAIL = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNION_MAIL", Value=4)]
      UNION_MAIL = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ARENA_MALL", Value=5)]
      ARENA_MALL = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CDKEY_MAIL", Value=6)]
      CDKEY_MAIL = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHAT_MALL", Value=7)]
      CHAT_MALL = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNION_KICK_MAIL", Value=8)]
      UNION_KICK_MAIL = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"APPEND_FRIENDS_MAIL", Value=9)]
      APPEND_FRIENDS_MAIL = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DONATE_FRIENDS_PH_MAIL", Value=10)]
      DONATE_FRIENDS_PH_MAIL = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MODIFY_APPLY_FRIENDS_MIAL", Value=11)]
      MODIFY_APPLY_FRIENDS_MIAL = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DELETE_FRIENDS_MAIL", Value=12)]
      DELETE_FRIENDS_MAIL = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVIET_CODE_TASK_MAIL", Value=13)]
      INVIET_CODE_TASK_MAIL = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RECHARGE_OFFLINE_MAIL", Value=14)]
      RECHARGE_OFFLINE_MAIL = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"POLE_LOG_MAIL", Value=15)]
      POLE_LOG_MAIL = 15
    }
  
}