//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Recyle.proto
// Note: requires additional types generated from: Base.proto
namespace fogs.proto.msg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RecycleReq")]
  public partial class RecycleReq : global::ProtoBuf.IExtensible
  {
    public RecycleReq() {}
    
    private fogs.proto.msg.RecycleType _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.RecycleType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private readonly global::System.Collections.Generic.List<ulong> _id = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(2, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> id
    {
      get { return _id; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RecycleResp")]
  public partial class RecycleResp : global::ProtoBuf.IExtensible
  {
    public RecycleResp() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private fogs.proto.msg.ItemInfo _update_money = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"update_money", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.ItemInfo update_money
    {
      get { return _update_money; }
      set { _update_money = value; }
    }
    private fogs.proto.msg.RecycleType _type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.RecycleType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.ItemInfo> _item_list = new global::System.Collections.Generic.List<fogs.proto.msg.ItemInfo>();
    [global::ProtoBuf.ProtoMember(4, Name=@"item_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.ItemInfo> item_list
    {
      get { return _item_list; }
    }
  
    private readonly global::System.Collections.Generic.List<ulong> _equip_list = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(5, Name=@"equip_list", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> equip_list
    {
      get { return _equip_list; }
    }
  
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.Equip> _equip_unload_list = new global::System.Collections.Generic.List<fogs.proto.msg.Equip>();
    [global::ProtoBuf.ProtoMember(6, Name=@"equip_unload_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.Equip> equip_unload_list
    {
      get { return _equip_unload_list; }
    }
  
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.LifeSoul> _life_unload_list = new global::System.Collections.Generic.List<fogs.proto.msg.LifeSoul>();
    [global::ProtoBuf.ProtoMember(7, Name=@"life_unload_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.LifeSoul> life_unload_list
    {
      get { return _life_unload_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}