//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ServerConfig.proto
// Note: requires additional types generated from: Login.proto
// Note: requires additional types generated from: DBInfo.proto
namespace fogs.proto.msg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServerInfo")]
  public partial class ServerInfo : global::ProtoBuf.IExtensible
  {
    public ServerInfo() {}
    
    private string _ip = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ip
    {
      get { return _ip; }
      set { _ip = value; }
    }
    private int _port = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int port
    {
      get { return _port; }
      set { _port = value; }
    }
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginServerCfg")]
  public partial class LoginServerCfg : global::ProtoBuf.IExtensible
  {
    public LoginServerCfg() {}
    
    private fogs.proto.msg.ServerInfo _host = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"host", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.ServerInfo host
    {
      get { return _host; }
      set { _host = value; }
    }
    private fogs.proto.msg.ServerInfo _account_conns = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"account_conns", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.ServerInfo account_conns
    {
      get { return _account_conns; }
      set { _account_conns = value; }
    }
    private uint _thread_count = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"thread_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint thread_count
    {
      get { return _thread_count; }
      set { _thread_count = value; }
    }
    private uint _login_timeout = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"login_timeout", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint login_timeout
    {
      get { return _login_timeout; }
      set { _login_timeout = value; }
    }
    private string _pem_dir = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"pem_dir", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string pem_dir
    {
      get { return _pem_dir; }
      set { _pem_dir = value; }
    }
    private string _game_version = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"game_version", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string game_version
    {
      get { return _game_version; }
      set { _game_version = value; }
    }
    private string _res_version = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"res_version", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string res_version
    {
      get { return _res_version; }
      set { _res_version = value; }
    }
    private string _res_url = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"res_url", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string res_url
    {
      get { return _res_url; }
      set { _res_url = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.ServerDetail> _server_list = new global::System.Collections.Generic.List<fogs.proto.msg.ServerDetail>();
    [global::ProtoBuf.ProtoMember(9, Name=@"server_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.ServerDetail> server_list
    {
      get { return _server_list; }
    }
  
    private fogs.proto.msg.ServerInfo _log = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"log", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.ServerInfo log
    {
      get { return _log; }
      set { _log = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GatewayServerCfg")]
  public partial class GatewayServerCfg : global::ProtoBuf.IExtensible
  {
    public GatewayServerCfg() {}
    
    private fogs.proto.msg.ServerInfo _host = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"host", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.ServerInfo host
    {
      get { return _host; }
      set { _host = value; }
    }
    private uint _thread_count = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"thread_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint thread_count
    {
      get { return _thread_count; }
      set { _thread_count = value; }
    }
    private fogs.proto.msg.ServerInfo _conn = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"conn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.ServerInfo conn
    {
      get { return _conn; }
      set { _conn = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.ServerDetail> _server_info = new global::System.Collections.Generic.List<fogs.proto.msg.ServerDetail>();
    [global::ProtoBuf.ProtoMember(6, Name=@"server_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.ServerDetail> server_info
    {
      get { return _server_info; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResCfg")]
  public partial class ResCfg : global::ProtoBuf.IExtensible
  {
    public ResCfg() {}
    
    private string _res_dir = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"res_dir", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string res_dir
    {
      get { return _res_dir; }
      set { _res_dir = value; }
    }
    private string _lua_dir = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"lua_dir", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string lua_dir
    {
      get { return _lua_dir; }
      set { _lua_dir = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameServerCfg")]
  public partial class GameServerCfg : global::ProtoBuf.IExtensible
  {
    public GameServerCfg() {}
    
    private fogs.proto.msg.ServerInfo _host = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"host", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.ServerInfo host
    {
      get { return _host; }
      set { _host = value; }
    }
    private fogs.proto.msg.ServerInfo _gamedb = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"gamedb", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.ServerInfo gamedb
    {
      get { return _gamedb; }
      set { _gamedb = value; }
    }
    private fogs.proto.msg.ServerInfo _log = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"log", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.ServerInfo log
    {
      get { return _log; }
      set { _log = value; }
    }
    private fogs.proto.msg.ServerInfo _rank = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.ServerInfo rank
    {
      get { return _rank; }
      set { _rank = value; }
    }
    private fogs.proto.msg.ServerInfo _connecter = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"connecter", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.ServerInfo connecter
    {
      get { return _connecter; }
      set { _connecter = value; }
    }
    private fogs.proto.msg.ResCfg _res = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"res", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.ResCfg res
    {
      get { return _res; }
      set { _res = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _login_urls = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(7, Name=@"login_urls", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> login_urls
    {
      get { return _login_urls; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DBServerCfg")]
  public partial class DBServerCfg : global::ProtoBuf.IExtensible
  {
    public DBServerCfg() {}
    
    private fogs.proto.msg.ServerInfo _host = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"host", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.ServerInfo host
    {
      get { return _host; }
      set { _host = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.DBInfo> _dbs = new global::System.Collections.Generic.List<fogs.proto.msg.DBInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"dbs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.DBInfo> dbs
    {
      get { return _dbs; }
    }
  
    private uint _table_num = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"table_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint table_num
    {
      get { return _table_num; }
      set { _table_num = value; }
    }
    private uint _thread_num = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"thread_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint thread_num
    {
      get { return _thread_num; }
      set { _thread_num = value; }
    }
    private uint _account_id = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"account_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint account_id
    {
      get { return _account_id; }
      set { _account_id = value; }
    }
    private uint _stdelay = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"stdelay", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint stdelay
    {
      get { return _stdelay; }
      set { _stdelay = value; }
    }
    private uint _stspace = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"stspace", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint stspace
    {
      get { return _stspace; }
      set { _stspace = value; }
    }
    private uint _stsrolenum = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"stsrolenum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint stsrolenum
    {
      get { return _stsrolenum; }
      set { _stsrolenum = value; }
    }
    private uint _stdlogouttime = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"stdlogouttime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint stdlogouttime
    {
      get { return _stdlogouttime; }
      set { _stdlogouttime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LogServerCfg")]
  public partial class LogServerCfg : global::ProtoBuf.IExtensible
  {
    public LogServerCfg() {}
    
    private fogs.proto.msg.ServerInfo _host = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"host", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.ServerInfo host
    {
      get { return _host; }
      set { _host = value; }
    }
    private fogs.proto.msg.DBInfo _db = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"db", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.DBInfo db
    {
      get { return _db; }
      set { _db = value; }
    }
    private fogs.proto.msg.DBInfo _bg_db = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"bg_db", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.DBInfo bg_db
    {
      get { return _bg_db; }
      set { _bg_db = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ConnecterServerCfg")]
  public partial class ConnecterServerCfg : global::ProtoBuf.IExtensible
  {
    public ConnecterServerCfg() {}
    
    private fogs.proto.msg.ServerInfo _host = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"host", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.ServerInfo host
    {
      get { return _host; }
      set { _host = value; }
    }
    private fogs.proto.msg.ServerInfo _game = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"game", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.ServerInfo game
    {
      get { return _game; }
      set { _game = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}