//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Shop.proto
// Note: requires additional types generated from: Base.proto
namespace fogs.proto.msg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpdateShopReq")]
  public partial class UpdateShopReq : global::ProtoBuf.IExtensible
  {
    public UpdateShopReq() {}
    
    private fogs.proto.msg.UpdateType _update_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"update_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.UpdateType update_type
    {
      get { return _update_type; }
      set { _update_type = value; }
    }
    private fogs.proto.msg.ShopType _shop_type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"shop_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.ShopType shop_type
    {
      get { return _shop_type; }
      set { _shop_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CommodityInfo")]
  public partial class CommodityInfo : global::ProtoBuf.IExtensible
  {
    public CommodityInfo() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _num = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int num
    {
      get { return _num; }
      set { _num = value; }
    }
    private int _sell_out = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"sell_out", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sell_out
    {
      get { return _sell_out; }
      set { _sell_out = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ShopInfo")]
  public partial class ShopInfo : global::ProtoBuf.IExtensible
  {
    public ShopInfo() {}
    
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.CommodityInfo> _commodity_info = new global::System.Collections.Generic.List<fogs.proto.msg.CommodityInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"commodity_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.CommodityInfo> commodity_info
    {
      get { return _commodity_info; }
    }
  
    private fogs.proto.msg.ShopType _shop_type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"shop_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.ShopType shop_type
    {
      get { return _shop_type; }
      set { _shop_type = value; }
    }
    private ulong _next_update_time = default(ulong);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"next_update_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong next_update_time
    {
      get { return _next_update_time; }
      set { _next_update_time = value; }
    }
    private int _hand_update_num = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"hand_update_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int hand_update_num
    {
      get { return _hand_update_num; }
      set { _hand_update_num = value; }
    }
    private ulong _last_update_time = default(ulong);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"last_update_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong last_update_time
    {
      get { return _last_update_time; }
      set { _last_update_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpdateShopResp")]
  public partial class UpdateShopResp : global::ProtoBuf.IExtensible
  {
    public UpdateShopResp() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private fogs.proto.msg.ShopInfo _shop_info = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"shop_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.ShopInfo shop_info
    {
      get { return _shop_info; }
      set { _shop_info = value; }
    }
    private fogs.proto.msg.ItemInfo _money_iteminfo = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"money_iteminfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.ItemInfo money_iteminfo
    {
      get { return _money_iteminfo; }
      set { _money_iteminfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuyCommodityReq")]
  public partial class BuyCommodityReq : global::ProtoBuf.IExtensible
  {
    public BuyCommodityReq() {}
    
    private fogs.proto.msg.ShopType _shop_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"shop_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.ShopType shop_type
    {
      get { return _shop_type; }
      set { _shop_type = value; }
    }
    private int _commodity_id = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"commodity_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int commodity_id
    {
      get { return _commodity_id; }
      set { _commodity_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuyCommodityResp")]
  public partial class BuyCommodityResp : global::ProtoBuf.IExtensible
  {
    public BuyCommodityResp() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int _commodity_id = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"commodity_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int commodity_id
    {
      get { return _commodity_id; }
      set { _commodity_id = value; }
    }
    private fogs.proto.msg.ShopType _shop_type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"shop_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.ShopType shop_type
    {
      get { return _shop_type; }
      set { _shop_type = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.ItemInfo> _update_item = new global::System.Collections.Generic.List<fogs.proto.msg.ItemInfo>();
    [global::ProtoBuf.ProtoMember(4, Name=@"update_item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.ItemInfo> update_item
    {
      get { return _update_item; }
    }
  
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.Equip> _update_equip = new global::System.Collections.Generic.List<fogs.proto.msg.Equip>();
    [global::ProtoBuf.ProtoMember(5, Name=@"update_equip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.Equip> update_equip
    {
      get { return _update_equip; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuyAllCommodityReq")]
  public partial class BuyAllCommodityReq : global::ProtoBuf.IExtensible
  {
    public BuyAllCommodityReq() {}
    
    private fogs.proto.msg.ShopType _shop_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"shop_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.ShopType shop_type
    {
      get { return _shop_type; }
      set { _shop_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuyAllCommodityResp")]
  public partial class BuyAllCommodityResp : global::ProtoBuf.IExtensible
  {
    public BuyAllCommodityResp() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _commodity_id = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"commodity_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> commodity_id
    {
      get { return _commodity_id; }
    }
  
    private fogs.proto.msg.ShopType _shop_type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"shop_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.ShopType shop_type
    {
      get { return _shop_type; }
      set { _shop_type = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.ItemInfo> _update_item = new global::System.Collections.Generic.List<fogs.proto.msg.ItemInfo>();
    [global::ProtoBuf.ProtoMember(4, Name=@"update_item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.ItemInfo> update_item
    {
      get { return _update_item; }
    }
  
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.Equip> _update_equip = new global::System.Collections.Generic.List<fogs.proto.msg.Equip>();
    [global::ProtoBuf.ProtoMember(5, Name=@"update_equip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.Equip> update_equip
    {
      get { return _update_equip; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuySpecialCommodityReq")]
  public partial class BuySpecialCommodityReq : global::ProtoBuf.IExtensible
  {
    public BuySpecialCommodityReq() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _num = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int num
    {
      get { return _num; }
      set { _num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuySpecialCommodityResp")]
  public partial class BuySpecialCommodityResp : global::ProtoBuf.IExtensible
  {
    public BuySpecialCommodityResp() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int _commodity_id = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"commodity_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int commodity_id
    {
      get { return _commodity_id; }
      set { _commodity_id = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.ItemInfo> _update_item = new global::System.Collections.Generic.List<fogs.proto.msg.ItemInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"update_item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.ItemInfo> update_item
    {
      get { return _update_item; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"UpdateType")]
    public enum UpdateType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UT_AUTO", Value=1)]
      UT_AUTO = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UT_COST", Value=2)]
      UT_COST = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ShopType")]
    public enum ShopType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ST_NomalShop", Value=1)]
      ST_NomalShop = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ST_MedalShop", Value=2)]
      ST_MedalShop = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ST_HonorShop", Value=3)]
      ST_HonorShop = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ST_UnionShop", Value=4)]
      ST_UnionShop = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ST_ECShlp", Value=5)]
      ST_ECShlp = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ST_RecycleShop", Value=6)]
      ST_RecycleShop = 6
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"GoodsConfigType")]
    public enum GoodsConfigType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"GCT_Equip", Value=2)]
      GCT_Equip = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GCT_Item", Value=3)]
      GCT_Item = 3
    }
  
}