//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Soldier.proto
// Note: requires additional types generated from: Base.proto
namespace fogs.proto.msg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoldierUpStarReq")]
  public partial class SoldierUpStarReq : global::ProtoBuf.IExtensible
  {
    public SoldierUpStarReq() {}
    
    private ulong _uid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private ulong _material_uid = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"material_uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong material_uid
    {
      get { return _material_uid; }
      set { _material_uid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoldierUpStarResp")]
  public partial class SoldierUpStarResp : global::ProtoBuf.IExtensible
  {
    public SoldierUpStarResp() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private ulong _material_uid = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"material_uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong material_uid
    {
      get { return _material_uid; }
      set { _material_uid = value; }
    }
    private int _money_type = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"money_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int money_type
    {
      get { return _money_type; }
      set { _money_type = value; }
    }
    private int _money_num = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"money_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int money_num
    {
      get { return _money_num; }
      set { _money_num = value; }
    }
    private fogs.proto.msg.Soldier _soldier_info = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"soldier_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.Soldier soldier_info
    {
      get { return _soldier_info; }
      set { _soldier_info = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.ItemInfo> _skill_return_item = new global::System.Collections.Generic.List<fogs.proto.msg.ItemInfo>();
    [global::ProtoBuf.ProtoMember(6, Name=@"skill_return_item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.ItemInfo> skill_return_item
    {
      get { return _skill_return_item; }
    }
  
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.Equip> _equip_list = new global::System.Collections.Generic.List<fogs.proto.msg.Equip>();
    [global::ProtoBuf.ProtoMember(7, Name=@"equip_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.Equip> equip_list
    {
      get { return _equip_list; }
    }
  
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.LifeSoul> _soul_return_item = new global::System.Collections.Generic.List<fogs.proto.msg.LifeSoul>();
    [global::ProtoBuf.ProtoMember(8, Name=@"soul_return_item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.LifeSoul> soul_return_item
    {
      get { return _soul_return_item; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoldierUpLvReq")]
  public partial class SoldierUpLvReq : global::ProtoBuf.IExtensible
  {
    public SoldierUpLvReq() {}
    
    private ulong _uid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private readonly global::System.Collections.Generic.List<ulong> _uid_list = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(2, Name=@"uid_list", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> uid_list
    {
      get { return _uid_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoldierUpLvResp")]
  public partial class SoldierUpLvResp : global::ProtoBuf.IExtensible
  {
    public SoldierUpLvResp() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private readonly global::System.Collections.Generic.List<ulong> _uid_list = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(2, Name=@"uid_list", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> uid_list
    {
      get { return _uid_list; }
    }
  
    private int _money_type = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"money_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int money_type
    {
      get { return _money_type; }
      set { _money_type = value; }
    }
    private int _money_num = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"money_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int money_num
    {
      get { return _money_num; }
      set { _money_num = value; }
    }
    private fogs.proto.msg.Soldier _soldier_info = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"soldier_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.Soldier soldier_info
    {
      get { return _soldier_info; }
      set { _soldier_info = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.ItemInfo> _skill_return_item = new global::System.Collections.Generic.List<fogs.proto.msg.ItemInfo>();
    [global::ProtoBuf.ProtoMember(6, Name=@"skill_return_item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.ItemInfo> skill_return_item
    {
      get { return _skill_return_item; }
    }
  
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.Equip> _equip_list = new global::System.Collections.Generic.List<fogs.proto.msg.Equip>();
    [global::ProtoBuf.ProtoMember(7, Name=@"equip_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.Equip> equip_list
    {
      get { return _equip_list; }
    }
  
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.LifeSoul> _soul_return_item = new global::System.Collections.Generic.List<fogs.proto.msg.LifeSoul>();
    [global::ProtoBuf.ProtoMember(8, Name=@"soul_return_item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.LifeSoul> soul_return_item
    {
      get { return _soul_return_item; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoldierSelectReq")]
  public partial class SoldierSelectReq : global::ProtoBuf.IExtensible
  {
    public SoldierSelectReq() {}
    
    private readonly global::System.Collections.Generic.List<ulong> _uid_list = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(1, Name=@"uid_list", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> uid_list
    {
      get { return _uid_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoldierSelectResp")]
  public partial class SoldierSelectResp : global::ProtoBuf.IExtensible
  {
    public SoldierSelectResp() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private readonly global::System.Collections.Generic.List<ulong> _uid_list = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(2, Name=@"uid_list", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> uid_list
    {
      get { return _uid_list; }
    }
  
    private int _money_type = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"money_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int money_type
    {
      get { return _money_type; }
      set { _money_type = value; }
    }
    private int _money_num = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"money_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int money_num
    {
      get { return _money_num; }
      set { _money_num = value; }
    }
    private fogs.proto.msg.Soldier _soldier_info = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"soldier_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.Soldier soldier_info
    {
      get { return _soldier_info; }
      set { _soldier_info = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.ItemInfo> _skill_return_item = new global::System.Collections.Generic.List<fogs.proto.msg.ItemInfo>();
    [global::ProtoBuf.ProtoMember(6, Name=@"skill_return_item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.ItemInfo> skill_return_item
    {
      get { return _skill_return_item; }
    }
  
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.Equip> _equip_list = new global::System.Collections.Generic.List<fogs.proto.msg.Equip>();
    [global::ProtoBuf.ProtoMember(7, Name=@"equip_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.Equip> equip_list
    {
      get { return _equip_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NotifyGetNewSoldier")]
  public partial class NotifyGetNewSoldier : global::ProtoBuf.IExtensible
  {
    public NotifyGetNewSoldier() {}
    
    private uint _soldier_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"soldier_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint soldier_id
    {
      get { return _soldier_id; }
      set { _soldier_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoldierUpLevelStarReq")]
  public partial class SoldierUpLevelStarReq : global::ProtoBuf.IExtensible
  {
    public SoldierUpLevelStarReq() {}
    
    private ulong _uid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private readonly global::System.Collections.Generic.List<ulong> _material_uid = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(2, Name=@"material_uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> material_uid
    {
      get { return _material_uid; }
    }
  
    private readonly global::System.Collections.Generic.List<ulong> _material_uid_list = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(3, Name=@"material_uid_list", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> material_uid_list
    {
      get { return _material_uid_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoldierUpLevelStarResp")]
  public partial class SoldierUpLevelStarResp : global::ProtoBuf.IExtensible
  {
    public SoldierUpLevelStarResp() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private readonly global::System.Collections.Generic.List<ulong> _material_uid = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(2, Name=@"material_uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> material_uid
    {
      get { return _material_uid; }
    }
  
    private int _money_type = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"money_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int money_type
    {
      get { return _money_type; }
      set { _money_type = value; }
    }
    private int _money_num = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"money_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int money_num
    {
      get { return _money_num; }
      set { _money_num = value; }
    }
    private fogs.proto.msg.Soldier _soldier_info = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"soldier_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.Soldier soldier_info
    {
      get { return _soldier_info; }
      set { _soldier_info = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.ItemInfo> _skill_return_item = new global::System.Collections.Generic.List<fogs.proto.msg.ItemInfo>();
    [global::ProtoBuf.ProtoMember(6, Name=@"skill_return_item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.ItemInfo> skill_return_item
    {
      get { return _skill_return_item; }
    }
  
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.Equip> _equip_list = new global::System.Collections.Generic.List<fogs.proto.msg.Equip>();
    [global::ProtoBuf.ProtoMember(7, Name=@"equip_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.Equip> equip_list
    {
      get { return _equip_list; }
    }
  
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.LifeSoul> _soul_return_item = new global::System.Collections.Generic.List<fogs.proto.msg.LifeSoul>();
    [global::ProtoBuf.ProtoMember(8, Name=@"soul_return_item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.LifeSoul> soul_return_item
    {
      get { return _soul_return_item; }
    }
  
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.Soldier> _return_soldiers = new global::System.Collections.Generic.List<fogs.proto.msg.Soldier>();
    [global::ProtoBuf.ProtoMember(9, Name=@"return_soldiers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.Soldier> return_soldiers
    {
      get { return _return_soldiers; }
    }
  
    private int _return_overflow = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"return_overflow", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int return_overflow
    {
      get { return _return_overflow; }
      set { _return_overflow = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoldierUpQualityReq")]
  public partial class SoldierUpQualityReq : global::ProtoBuf.IExtensible
  {
    public SoldierUpQualityReq() {}
    
    private fogs.proto.msg.SoldierUpQualityType _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.SoldierUpQualityType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private readonly global::System.Collections.Generic.List<ulong> _uid_list = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(2, Name=@"uid_list", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> uid_list
    {
      get { return _uid_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoldierUpQualityResp")]
  public partial class SoldierUpQualityResp : global::ProtoBuf.IExtensible
  {
    public SoldierUpQualityResp() {}
    
    private uint _result = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private readonly global::System.Collections.Generic.List<ulong> _uid_list = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(2, Name=@"uid_list", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> uid_list
    {
      get { return _uid_list; }
    }
  
    private int _soldier_quality_value = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"soldier_quality_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int soldier_quality_value
    {
      get { return _soldier_quality_value; }
      set { _soldier_quality_value = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.Soldier> _soldier_list = new global::System.Collections.Generic.List<fogs.proto.msg.Soldier>();
    [global::ProtoBuf.ProtoMember(4, Name=@"soldier_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.Soldier> soldier_list
    {
      get { return _soldier_list; }
    }
  
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.Equip> _equip_list = new global::System.Collections.Generic.List<fogs.proto.msg.Equip>();
    [global::ProtoBuf.ProtoMember(5, Name=@"equip_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.Equip> equip_list
    {
      get { return _equip_list; }
    }
  
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.ItemInfo> _item_list = new global::System.Collections.Generic.List<fogs.proto.msg.ItemInfo>();
    [global::ProtoBuf.ProtoMember(6, Name=@"item_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.ItemInfo> item_list
    {
      get { return _item_list; }
    }
  
    private int _gold_num = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"gold_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gold_num
    {
      get { return _gold_num; }
      set { _gold_num = value; }
    }
    private fogs.proto.msg.SoldierUpQualityType _type;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public fogs.proto.msg.SoldierUpQualityType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.LifeSoul> _soul_return_item = new global::System.Collections.Generic.List<fogs.proto.msg.LifeSoul>();
    [global::ProtoBuf.ProtoMember(9, Name=@"soul_return_item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.LifeSoul> soul_return_item
    {
      get { return _soul_return_item; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoldierUpStepReq")]
  public partial class SoldierUpStepReq : global::ProtoBuf.IExtensible
  {
    public SoldierUpStepReq() {}
    
    private ulong _uid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private readonly global::System.Collections.Generic.List<ulong> _material_uid = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(2, Name=@"material_uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> material_uid
    {
      get { return _material_uid; }
    }
  
    private readonly global::System.Collections.Generic.List<ulong> _material_uid_list = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(3, Name=@"material_uid_list", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> material_uid_list
    {
      get { return _material_uid_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoldierUpStepResp")]
  public partial class SoldierUpStepResp : global::ProtoBuf.IExtensible
  {
    public SoldierUpStepResp() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private readonly global::System.Collections.Generic.List<ulong> _material_uid = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(2, Name=@"material_uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> material_uid
    {
      get { return _material_uid; }
    }
  
    private int _money_type = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"money_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int money_type
    {
      get { return _money_type; }
      set { _money_type = value; }
    }
    private int _money_num = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"money_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int money_num
    {
      get { return _money_num; }
      set { _money_num = value; }
    }
    private fogs.proto.msg.Soldier _soldier_info = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"soldier_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fogs.proto.msg.Soldier soldier_info
    {
      get { return _soldier_info; }
      set { _soldier_info = value; }
    }
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.ItemInfo> _skill_return_item = new global::System.Collections.Generic.List<fogs.proto.msg.ItemInfo>();
    [global::ProtoBuf.ProtoMember(6, Name=@"skill_return_item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.ItemInfo> skill_return_item
    {
      get { return _skill_return_item; }
    }
  
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.Equip> _equip_list = new global::System.Collections.Generic.List<fogs.proto.msg.Equip>();
    [global::ProtoBuf.ProtoMember(7, Name=@"equip_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.Equip> equip_list
    {
      get { return _equip_list; }
    }
  
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.LifeSoul> _soul_return_item = new global::System.Collections.Generic.List<fogs.proto.msg.LifeSoul>();
    [global::ProtoBuf.ProtoMember(8, Name=@"soul_return_item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.LifeSoul> soul_return_item
    {
      get { return _soul_return_item; }
    }
  
    private readonly global::System.Collections.Generic.List<fogs.proto.msg.Soldier> _return_soldiers = new global::System.Collections.Generic.List<fogs.proto.msg.Soldier>();
    [global::ProtoBuf.ProtoMember(9, Name=@"return_soldiers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fogs.proto.msg.Soldier> return_soldiers
    {
      get { return _return_soldiers; }
    }
  
    private int _return_overflow = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"return_overflow", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int return_overflow
    {
      get { return _return_overflow; }
      set { _return_overflow = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"SoldierUpQualityType")]
    public enum SoldierUpQualityType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Soldier_RED", Value=1)]
      Soldier_RED = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Soldier_ORA", Value=2)]
      Soldier_ORA = 2
    }
  
}