using UnityEngine;
using System;
using System.Collections;

public class CrossServerWarView
{
    public static string UIName ="CrossServerWarView";
    public GameObject _uiRoot;
    //======================================================================战场
    public Transform Trans_BattleField;
    public Transform Trans_ShowField;
    //public UIDragScrollView Drag_BattleField;
    public Transform Trans_BattleFieldSprite;
    //public UISprite Spt_ItemSprite;
    public GameObject Gobj_TileItem;
    public Transform Trans_TileGrid;
    public UIScrollView Scro_BattleField;
    //======================================================================主界面UI
    //public UIPanel UIPanel_ButtonGroup;
    //public UISprite Spt_QuitButton;
    public UIButton Btn_QuitButton;
    //public UISprite Spt_RankListButton;
    public UIButton Btn_RankListButton;
    //public UILabel Lbl_BtnRankListButtonRankListLabel;
    //public UISprite Spt_RuleButton;
    public UIButton Btn_RuleButton;
    //public UILabel Lbl_BtnRuleButtonRuleLabel;
    public UISprite Spt_BattleCountdown;
    public UILabel Lbl_BattleCountdownDesc;
    public UISprite Spt_RestCountdown;
    public UILabel Lbl_RestCountdownDesc;
    //public UISprite Spt_SearchTile;
    public UIInput Ipt_SearchTile;
    //public UISprite Spt_InputSearchTileSearchButton;
    public UIButton Btn_InputSearchTileSearchButton;
    //public UILabel Lbl_BtnSearchButtonSearchLabel;
    public UILabel Lbl_InputSearchTileSearchID;
    //public UISprite Spt_OverviewButton;
    public UIButton Btn_OverviewButton;
    //public UISprite Spt_DetailviewButton;
    public UIButton Btn_DetailviewButton;
    //public UISprite Spt_InformationButton;
    public UIButton Btn_InformationButton;
    //public UISprite Spt_UnionButton;
    public UIButton Btn_UnionButton;
    //==========================================================================规则
    public GameObject Gobj_Rule;
    //public UIPanel UIPanel_Rule;
    //public UIPanel UIPanel_RuleDesc;
    public UIScrollView ScrView_RuleDesc;
    public UILabel Lbl_RuleDesc;
    //public UISprite Spt_Bg;
    //public UILabel Lbl_TitleLabel;
    //public UISprite Spt_LeftTitleBG;
    //public UISprite Spt_RightTitleBG;
    //public UISprite Spt_RuleBg;
    //public UISprite Spt_CloseRuleButton;
    public UIButton Btn_CloseRuleButton;
    public UISprite Spt_RuleMask;
    //===========================================================================地块信息
    public GameObject Gobj_TileInfo;
    //public UIPanel UIPanel_TileInfo;
    //public UISprite Spt_BG;
    //public UISprite Spt_Left1;
    //public UISprite Spt_Right1;
    //public UISprite Spt_Left2;
    //public UISprite Spt_Right2;
    //public UISprite Spt_Flower1;
    //public UISprite Spt_Flower2;
    //public UISprite Spt_TitleRightBG;
    //public UISprite Spt_TitleLiftBG;
    public UILabel Lbl_TileTitle;
    //public UIPanel UIPanel_ScoreItems;
    //public UIScrollView ScrView_ScoreItems;
    public UIGrid Grd_TileRankGrid;
    //public UILabel Lbl_TitleScore;
    public UILabel Lbl_TitleName;
    //public UILabel Lbl_TitleRank;
    //public UILabel Lbl_TitleAward;
    public GameObject Gobj_TileRank;
    public UISprite Spt_Selected;
    public UILabel Lbl_MyRank;
    public UILabel Lbl_MyName;
    public UILabel Lbl_MyScore;
    public UIButton Btn_UnionRank;
    //public UISprite Spt_BtnUnionRankBackground;
    //public UILabel Lbl_BtnUnionRankLabel;
    //public UISprite Spt_BtnUnionRankfg;
    //public UISprite Spt_BtnUnionRankfg1;
    public UIButton Btn_PersonRank;
    //public UISprite Spt_BtnPersonRankBackground;
    //public UILabel Lbl_BtnPersonRankLabel;
    //public UISprite Spt_BtnPersonRankfg;
    //public UISprite Spt_BtnPersonRankfg1;
    //public UILabel Lbl_TileIDLabel;
    public UILabel Lbl_TileIDContent;
    //public UILabel Lbl_OwnerLabel;
    public UILabel Lbl_OwnerContent;
    //public UILabel Lbl_StateLabel;
    public UILabel Lbl_StateContent;
    //public UILabel Lbl_MilitarySuppliesLabel;
    public UILabel Lbl_MilitarySuppliesContent;
    //public UILabel Lbl_ControlTurnsLabel;
    public UILabel Lbl_ControlTurnstContent;
    public UILabel Lbl_SpecialProdutionLabel;
    public UIScrollView Scr_OutputPanel;
    public UIGrid Grd_SpecialProduction;
    public UILabel Lbl_FightCDTip;
    public UIButton Btn_Fight;
    //public UISprite Spt_BtnFightBackground;
    public UILabel Lbl_BtnFightLabel;
    //public UISprite Spt_CloseTileInfoButton;
    public UIButton Btn_CloseTileInfoButton;
    public UISprite Spt_TileInfoMask;
    //=================================================================================军团信息
    public GameObject Gobj_Union;
    //public UIPanel UIPanel_UnionInfo;
    public UISprite Spt_UnionInfoMask;
    //public UISprite Spt_BGSprite;
    //public UISprite Spt_ContextBGSprite;
    //public UILabel Lbl_TitleLabel;
    //public UISprite Spt_TitleLeftSprite;
    //public UISprite Spt_TitleRightSprite;
    //public UISprite Spt_NameBGSprite1;
    //public UISprite Spt_NameBGSprite2;
    public UILabel Lbl_UnionNameLabel;
    public UILabel Lbl_UnionLevelLabel;
    public UISprite Spt_IconFrame;
    public UISprite Spt_IconBG;
    public UISprite Spt_IconSprite;
    //public UILabel Lbl_PopulationLabel;
    public UILabel Lbl_PopulationtnContent;
    //public UILabel Lbl_MaterialLabel;
    public UILabel Lbl_MaterialContent;
    //public UILabel Lbl_NormalTerritoryLabel;
    public UILabel Lbl_NormalTerritoryContent;
    //public UILabel Lbl_SpecialTerritoryLabel;
    public UILabel Lbl_SpecialTerritoryContent;
    //public UILabel Lbl_FightTerritoryLabel;
    public UILabel Lbl_FightTerritoryContent;
    //public UILabel Lbl_MinProductionLabel;
    public UILabel Lbl_MinProdutionContent;
    //public UILabel Lbl_MaxProductionLabel;
    //public UILabel Lbl_MaxProdutionContent;
    //public UILabel Lbl_SpecialProductionLabel;
    public UIButton Btn_DetailInfoButton;
    //public UISprite Spt_DetailInfoButton;
    //public UILabel Lbl_BtnDetailInfoButtonDetailInfoSprite;
    //public UISprite Spt_CloseRuleButton;
    public UIButton Btn_CloseUnionInfoButton;
    //=====================================================================================特殊产出
    public GameObject Gobj_SpecialProduction;
    //public UIPanel UIPanel_SpecialProductionInfo;
    public UISprite Spt_SPInfoMask;
    //public UISprite Spt_BGSprite;
    //public UISprite Spt_ContextBGSprite;
    //public UILabel Lbl_TitleLabel;
    //public UISprite Spt_TitleLeftSprite;
    //public UISprite Spt_TitleRightSprite;
    //public UISprite Spt_TitleBarSprite;
    //public UILabel Lbl_TileIDTitle;
    //public UILabel Lbl_ProductionsTitle;
    //public UILabel Lbl_OwnerStateTitle;
    //public UISprite Spt_CloseRuleButton;
    public UIButton Btn_CloseSPOutputButton;
    public GameObject Gobj_OutputItem;
    //public UILabel Lbl_OwnerState;
    //public UILabel Lbl_Productions;
    //public UILabel Lbl_TileID;
    public UIPanel UIPanel_DetailInformation;
    //public UIScrollView ScrView_DetailInformation;
    public UITable Table_UnionOutputTable;
    //======================================================================================跨服（奖励）信息
    public GameObject Gobj_ServerInfo;
    //public UIPanel UIPanel_ServerInfo;
    //public UISprite Spt_TitleRightBG;
    //public UISprite Spt_TitleLiftBG;
    public UILabel Lbl_ServerTitle;
    //public UISprite Spt_CloseTileInfoButton;
    public UIButton Btn_CloseServerInfoButton;
    //public UISprite Spt_BG;
    //public UISprite Spt_ServerListBG;
    //public UISprite Spt_ServerTitleBG;
    //public UILabel Lbl_ServerNameTitle;
    public GameObject Gobj_ServerListBlock;
    public UILabel Lbl_ServerName;
    //public UIPanel UIPanel_ServerList;
    //public UIScrollView ScrView_ServerList;
    public UIGrid Grd_ServerListGrid;
    public Transform Trans_AwardListBlock;
    public UISprite Spt_AwardListBG;
    public UISprite Spt_AwardTitleBG;
    public UILabel Lbl_TitleAward;
    public UIButton Btn_BattleAward;
    public UISprite Spt_BtnBattleAwardBattleAwardBtn;
    public UILabel Lbl_BtnBattleAwardLabel;
    public UIButton Btn_SeasonAward;
    public UISprite Spt_BtnSeasonAwardSeasonAwardBtn;
    public UILabel Lbl_BtnSeasonAwardLabel;
    public UILabel Lbl_RankingLabel;
    public GameObject Gobj_RankingAwardItem;
    public UIGrid Grd_RankingGoods;
    //public UIPanel UIPanel_ShowAwards;
    public UIScrollView ScrView_ShowAwards;
    public UITable UITable_Table;
    //public UISprite Spt_BulletinBoardBg;
    public UILabel Lbl_Bulletin;
    public UISprite Spt_ServerInfoMask;
    //==========================================================================================(地块)战场信息
    public GameObject Gobj_StageInfo;
    public UIButton Btn_StageClose;
    public UILabel Lbl_TypeTitle;
    public UILabel Lbl_StageDesc;
    public UIGrid Grd_EnemyGrid;
    public GameObject Gobj_Enemy;
    public UISprite Spt_StageInfoMask;
    public UIButton Btn_ReadyBattle;
    public UILabel Lbl_GateCount;
    public UILabel Lbl_CorpsName;
    public UILabel Lbl_IntegralNum;
    public UILabel Lbl_MyIntegralNum;
    //==============================================================================================奖励物品
    public GameObject Gobj_AwardGoods;

    public void Initialize()
    {
        _uiRoot =  GameObject.Find("UISystem/UICamera/Anchor/Panel/CrossServerWarView");

        //======================================================================战场

        Trans_BattleField = _uiRoot.transform.FindChild("BattleField").gameObject.transform;
        Trans_ShowField = _uiRoot.transform.FindChild("BattleField/BattleFieldAnim").gameObject.transform;
        Trans_BattleFieldSprite = _uiRoot.transform.FindChild("BattleField/BattleFieldAnim/BattleFieldSprite");
        Gobj_TileItem = _uiRoot.transform.FindChild("BattleField/BattleFieldAnim/TileItem").gameObject;
        Trans_TileGrid = _uiRoot.transform.FindChild("BattleField/BattleFieldAnim/TileGrid");
        Scro_BattleField = _uiRoot.transform.FindChild("BattleField").gameObject.GetComponent<UIScrollView>();

        //======================================================================主界面UI
        //UIPanel_ButtonGroup = _uiRoot.transform.FindChild("ButtonGroup").gameObject.GetComponent<UIPanel>();
        //Spt_QuitButton = _uiRoot.transform.FindChild("ButtonGroup/ButtonGroupAnim/QuitButton").gameObject.GetComponent<UISprite>();
        Btn_QuitButton = _uiRoot.transform.FindChild("ButtonGroup/ButtonGroupAnim/QuitButton").gameObject.GetComponent<UIButton>();
        //Spt_RankListButton = _uiRoot.transform.FindChild("ButtonGroup/ButtonGroupAnim/RankListButton").gameObject.GetComponent<UISprite>();
        Btn_RankListButton = _uiRoot.transform.FindChild("ButtonGroup/ButtonGroupAnim/RankListButton").gameObject.GetComponent<UIButton>();
        //Lbl_BtnRankListButtonRankListLabel = _uiRoot.transform.FindChild("ButtonGroup/ButtonGroupAnim/RankListButton/RankListLabel").gameObject.GetComponent<UILabel>();
        //Spt_RuleButton = _uiRoot.transform.FindChild("ButtonGroup/ButtonGroupAnim/RuleButton").gameObject.GetComponent<UISprite>();
        Btn_RuleButton = _uiRoot.transform.FindChild("ButtonGroup/ButtonGroupAnim/RuleButton").gameObject.GetComponent<UIButton>();
        //Lbl_BtnRuleButtonRuleLabel = _uiRoot.transform.FindChild("ButtonGroup/ButtonGroupAnim/RuleButton/RuleLabel").gameObject.GetComponent<UILabel>();
        Spt_BattleCountdown = _uiRoot.transform.FindChild("ButtonGroup/ButtonGroupAnim/BattleCountdown").gameObject.GetComponent<UISprite>();
        Lbl_BattleCountdownDesc = _uiRoot.transform.FindChild("ButtonGroup/ButtonGroupAnim/BattleCountdown/BattleCountdownDesc").gameObject.GetComponent<UILabel>();
        Spt_RestCountdown = _uiRoot.transform.FindChild("ButtonGroup/ButtonGroupAnim/RestCountdown").gameObject.GetComponent<UISprite>();
        Lbl_RestCountdownDesc = _uiRoot.transform.FindChild("ButtonGroup/ButtonGroupAnim/RestCountdown/RestCountdownDesc").gameObject.GetComponent<UILabel>();
        //Spt_SearchTile = _uiRoot.transform.FindChild("ButtonGroup/ButtonGroupAnim/SearchTile").gameObject.GetComponent<UISprite>();
        Ipt_SearchTile = _uiRoot.transform.FindChild("ButtonGroup/ButtonGroupAnim/SearchTile").gameObject.GetComponent<UIInput>();
        //Spt_InputSearchTileSearchButton = _uiRoot.transform.FindChild("ButtonGroup/ButtonGroupAnim/SearchTile/SearchButton").gameObject.GetComponent<UISprite>();
        Btn_InputSearchTileSearchButton = _uiRoot.transform.FindChild("ButtonGroup/ButtonGroupAnim/SearchTile/SearchButton").gameObject.GetComponent<UIButton>();
        //Lbl_BtnSearchButtonSearchLabel = _uiRoot.transform.FindChild("ButtonGroup/ButtonGroupAnim/SearchTile/SearchButton/SearchLabel").gameObject.GetComponent<UILabel>();
        Lbl_InputSearchTileSearchID = _uiRoot.transform.FindChild("ButtonGroup/ButtonGroupAnim/SearchTile/SearchID").gameObject.GetComponent<UILabel>();
        //Spt_OverviewButton = _uiRoot.transform.FindChild("ButtonGroup/ButtonGroupAnim/OverviewButton").gameObject.GetComponent<UISprite>();
        Btn_OverviewButton = _uiRoot.transform.FindChild("ButtonGroup/ButtonGroupAnim/OverviewButton").gameObject.GetComponent<UIButton>();
        //Spt_DetailviewButton = _uiRoot.transform.FindChild("ButtonGroup/ButtonGroupAnim/DetailviewButton").gameObject.GetComponent<UISprite>();
        Btn_DetailviewButton = _uiRoot.transform.FindChild("ButtonGroup/ButtonGroupAnim/DetailviewButton").gameObject.GetComponent<UIButton>();
        //Spt_InformationButton = _uiRoot.transform.FindChild("ButtonGroup/ButtonGroupAnim/InformationButton").gameObject.GetComponent<UISprite>();
        Btn_InformationButton = _uiRoot.transform.FindChild("ButtonGroup/ButtonGroupAnim/InformationButton").gameObject.GetComponent<UIButton>();
        //Spt_UnionButton = _uiRoot.transform.FindChild("ButtonGroup/ButtonGroupAnim/UnionButton").gameObject.GetComponent<UISprite>();
        Btn_UnionButton = _uiRoot.transform.FindChild("ButtonGroup/ButtonGroupAnim/UnionButton").gameObject.GetComponent<UIButton>();

        //==========================================================================规则
        Gobj_Rule = _uiRoot.transform.FindChild("Rule").gameObject;
        //UIPanel_Rule = _uiRoot.transform.FindChild("Rule").gameObject.GetComponent<UIPanel>();
        //UIPanel_RuleDesc = _uiRoot.transform.FindChild("Rule/RuleAnim/RuleDesc").gameObject.GetComponent<UIPanel>();
        ScrView_RuleDesc = _uiRoot.transform.FindChild("Rule/RuleAnim/RuleDesc").gameObject.GetComponent<UIScrollView>();
        Lbl_RuleDesc = _uiRoot.transform.FindChild("Rule/RuleAnim/RuleDesc/RuleDesc").gameObject.GetComponent<UILabel>();
        //Spt_Bg = _uiRoot.transform.FindChild("Rule/RuleAnim/BGGroup/Bg").gameObject.GetComponent<UISprite>();
        //Lbl_TitleLabel = _uiRoot.transform.FindChild("Rule/RuleAnim/BGGroup/TitleGroup/TitleLabel").gameObject.GetComponent<UILabel>();
        //Spt_LeftTitleBG = _uiRoot.transform.FindChild("Rule/RuleAnim/BGGroup/TitleGroup/LeftTitleBG").gameObject.GetComponent<UISprite>();
        //Spt_RightTitleBG = _uiRoot.transform.FindChild("Rule/RuleAnim/BGGroup/TitleGroup/RightTitleBG").gameObject.GetComponent<UISprite>();
        //Spt_RuleBg = _uiRoot.transform.FindChild("Rule/RuleAnim/BGGroup/RuleBg").gameObject.GetComponent<UISprite>();
        //Spt_CloseRuleButton = _uiRoot.transform.FindChild("Rule/RuleAnim/CloseRuleButton").gameObject.GetComponent<UISprite>();
        Btn_CloseRuleButton = _uiRoot.transform.FindChild("Rule/RuleAnim/CloseRuleButton").gameObject.GetComponent<UIButton>();
        Spt_RuleMask = _uiRoot.transform.FindChild("Rule/RuleMask").gameObject.GetComponent<UISprite>();

        //===========================================================================地块信息
        Gobj_TileInfo = _uiRoot.transform.FindChild("TileInfo").gameObject;
        //UIPanel_TileInfo = _uiRoot.transform.FindChild("TileInfo").gameObject.GetComponent<UIPanel>();
        //Spt_BG = _uiRoot.transform.FindChild("TileInfo/TileInfoAnim/BGS/BG").gameObject.GetComponent<UISprite>();
        //Spt_Left1 = _uiRoot.transform.FindChild("TileInfo/TileInfoAnim/BGS/Left1").gameObject.GetComponent<UISprite>();
        //Spt_Right1 = _uiRoot.transform.FindChild("TileInfo/TileInfoAnim/BGS/Right1").gameObject.GetComponent<UISprite>();
        //Spt_Left2 = _uiRoot.transform.FindChild("TileInfo/TileInfoAnim/BGS/Left2").gameObject.GetComponent<UISprite>();
        //Spt_Right2 = _uiRoot.transform.FindChild("TileInfo/TileInfoAnim/BGS/Right2").gameObject.GetComponent<UISprite>();
        //Spt_Flower1 = _uiRoot.transform.FindChild("TileInfo/TileInfoAnim/BGS/Flower1").gameObject.GetComponent<UISprite>();
        //Spt_Flower2 = _uiRoot.transform.FindChild("TileInfo/TileInfoAnim/BGS/Flower2").gameObject.GetComponent<UISprite>();
        //Spt_TitleRightBG = _uiRoot.transform.FindChild("TileInfo/TileInfoAnim/TitleObj/TitleRightBG").gameObject.GetComponent<UISprite>();
        //Spt_TitleLiftBG = _uiRoot.transform.FindChild("TileInfo/TileInfoAnim/TitleObj/TitleLiftBG").gameObject.GetComponent<UISprite>();
        Lbl_TileTitle = _uiRoot.transform.FindChild("TileInfo/TileInfoAnim/TitleObj/TileTitle").gameObject.GetComponent<UILabel>();
        //UIPanel_ScoreItems = _uiRoot.transform.FindChild("TileInfo/TileInfoAnim/ScoreItems").gameObject.GetComponent<UIPanel>();
        //ScrView_ScoreItems = _uiRoot.transform.FindChild("TileInfo/TileInfoAnim/ScoreItems").gameObject.GetComponent<UIScrollView>();
        Grd_TileRankGrid = _uiRoot.transform.FindChild("TileInfo/TileInfoAnim/ScoreItems/TileRankGrid").gameObject.GetComponent<UIGrid>();
        //Lbl_TitleScore = _uiRoot.transform.FindChild("TileInfo/TileInfoAnim/TitleLabels/TitleScore").gameObject.GetComponent<UILabel>();
        Lbl_TitleName = _uiRoot.transform.FindChild("TileInfo/TileInfoAnim/TitleLabels/TitleName").gameObject.GetComponent<UILabel>();
        //Lbl_TitleRank = _uiRoot.transform.FindChild("TileInfo/TileInfoAnim/TitleLabels/TitleRank").gameObject.GetComponent<UILabel>();
        //Lbl_TitleAward = _uiRoot.transform.FindChild("TileInfo/TileInfoAnim/TitleLabels/TitleAward").gameObject.GetComponent<UILabel>();
        //Lbl_Rank = _uiRoot.transform.FindChild("TileInfo/TileInfoAnim/Pre/RankScoreItem/Rank").gameObject.GetComponent<UILabel>();
        //Lbl_Name = _uiRoot.transform.FindChild("TileInfo/TileInfoAnim/Pre/RankScoreItem/Name").gameObject.GetComponent<UILabel>();
        //Lbl_Score = _uiRoot.transform.FindChild("TileInfo/TileInfoAnim/Pre/RankScoreItem/Score").gameObject.GetComponent<UILabel>();
        Gobj_TileRank = _uiRoot.transform.FindChild("TileInfo/TileInfoAnim/Pre/RankScoreItem").gameObject;
        Spt_Selected = _uiRoot.transform.FindChild("TileInfo/TileInfoAnim/Left/Selected").gameObject.GetComponent<UISprite>();
        Lbl_MyRank = _uiRoot.transform.FindChild("TileInfo/TileInfoAnim/Left/MyScore/Rank").gameObject.GetComponent<UILabel>();
        Lbl_MyName = _uiRoot.transform.FindChild("TileInfo/TileInfoAnim/Left/MyScore/Name").gameObject.GetComponent<UILabel>();
        Lbl_MyScore = _uiRoot.transform.FindChild("TileInfo/TileInfoAnim/Left/MyScore/Score").gameObject.GetComponent<UILabel>();
        Btn_UnionRank = _uiRoot.transform.FindChild("TileInfo/TileInfoAnim/Left/UnionRank").gameObject.GetComponent<UIButton>();
        //Spt_BtnUnionRankBackground = _uiRoot.transform.FindChild("TileInfo/TileInfoAnim/Left/UnionRank/Background").gameObject.GetComponent<UISprite>();
        //Lbl_BtnUnionRankLabel = _uiRoot.transform.FindChild("TileInfo/TileInfoAnim/Left/UnionRank/Label").gameObject.GetComponent<UILabel>();
        //Spt_BtnUnionRankfg = _uiRoot.transform.FindChild("TileInfo/TileInfoAnim/Left/UnionRank/fg").gameObject.GetComponent<UISprite>();
        //Spt_BtnUnionRankfg1 = _uiRoot.transform.FindChild("TileInfo/TileInfoAnim/Left/UnionRank/fg1").gameObject.GetComponent<UISprite>();
        Btn_PersonRank = _uiRoot.transform.FindChild("TileInfo/TileInfoAnim/Left/PersonRank").gameObject.GetComponent<UIButton>();
        //Spt_BtnPersonRankBackground = _uiRoot.transform.FindChild("TileInfo/TileInfoAnim/Left/PersonRank/Background").gameObject.GetComponent<UISprite>();
        //Lbl_BtnPersonRankLabel = _uiRoot.transform.FindChild("TileInfo/TileInfoAnim/Left/PersonRank/Label").gameObject.GetComponent<UILabel>();
        //Spt_BtnPersonRankfg = _uiRoot.transform.FindChild("TileInfo/TileInfoAnim/Left/PersonRank/fg").gameObject.GetComponent<UISprite>();
        //Spt_BtnPersonRankfg1 = _uiRoot.transform.FindChild("TileInfo/TileInfoAnim/Left/PersonRank/fg1").gameObject.GetComponent<UISprite>();
        //Lbl_TileIDLabel = _uiRoot.transform.FindChild("TileInfo/TileInfoAnim/Right/TileIDLabel").gameObject.GetComponent<UILabel>();
        Lbl_TileIDContent = _uiRoot.transform.FindChild("TileInfo/TileInfoAnim/Right/TileIDContent").gameObject.GetComponent<UILabel>();
        //Lbl_OwnerLabel = _uiRoot.transform.FindChild("TileInfo/TileInfoAnim/Right/OwnerLabel").gameObject.GetComponent<UILabel>();
        Lbl_OwnerContent = _uiRoot.transform.FindChild("TileInfo/TileInfoAnim/Right/OwnerContent").gameObject.GetComponent<UILabel>();
        //Lbl_StateLabel = _uiRoot.transform.FindChild("TileInfo/TileInfoAnim/Right/StateLabel").gameObject.GetComponent<UILabel>();
        Lbl_StateContent = _uiRoot.transform.FindChild("TileInfo/TileInfoAnim/Right/StateContent").gameObject.GetComponent<UILabel>();
        //Lbl_MilitarySuppliesLabel = _uiRoot.transform.FindChild("TileInfo/TileInfoAnim/Right/MilitarySuppliesLabel").gameObject.GetComponent<UILabel>();
        Lbl_MilitarySuppliesContent = _uiRoot.transform.FindChild("TileInfo/TileInfoAnim/Right/MilitarySuppliesContent").gameObject.GetComponent<UILabel>();
        //Lbl_ControlTurnsLabel = _uiRoot.transform.FindChild("TileInfo/TileInfoAnim/Right/ControlTurnsLabel").gameObject.GetComponent<UILabel>();
        Lbl_ControlTurnstContent = _uiRoot.transform.FindChild("TileInfo/TileInfoAnim/Right/ControlTurnstContent").gameObject.GetComponent<UILabel>();
        Lbl_SpecialProdutionLabel = _uiRoot.transform.FindChild("TileInfo/TileInfoAnim/Right/SpecialProdutionLabel").gameObject.GetComponent<UILabel>();
        Scr_OutputPanel = _uiRoot.transform.FindChild("TileInfo/TileInfoAnim/Right/OutPutPanel").gameObject.GetComponent<UIScrollView>();
        Grd_SpecialProduction = _uiRoot.transform.FindChild("TileInfo/TileInfoAnim/Right/OutPutPanel/SpecialProduction").gameObject.GetComponent<UIGrid>();
        Lbl_FightCDTip = _uiRoot.transform.FindChild("TileInfo/TileInfoAnim/Right/FightCDTip").gameObject.GetComponent<UILabel>();
        Btn_Fight = _uiRoot.transform.FindChild("TileInfo/TileInfoAnim/Right/Fight").gameObject.GetComponent<UIButton>();
        //Spt_BtnFightBackground = _uiRoot.transform.FindChild("TileInfo/TileInfoAnim/Right/Fight/Background").gameObject.GetComponent<UISprite>();
        Lbl_BtnFightLabel = _uiRoot.transform.FindChild("TileInfo/TileInfoAnim/Right/Fight/Label").gameObject.GetComponent<UILabel>();
        //Spt_CloseTileInfoButton = _uiRoot.transform.FindChild("TileInfo/TileInfoAnim/CloseTileInfoButton").gameObject.GetComponent<UISprite>();
        Btn_CloseTileInfoButton = _uiRoot.transform.FindChild("TileInfo/TileInfoAnim/CloseTileInfoButton").gameObject.GetComponent<UIButton>();
        Spt_TileInfoMask = _uiRoot.transform.FindChild("TileInfo/TileInfoMask").gameObject.GetComponent<UISprite>();

        //=================================================================================军团信息
        Gobj_Union = _uiRoot.transform.FindChild("UnionInfo").gameObject;
        //UIPanel_UnionInfo = _uiRoot.transform.FindChild("UnionInfo").gameObject.GetComponent<UIPanel>();
        Spt_UnionInfoMask = _uiRoot.transform.FindChild("UnionInfo/UnionInfoMask").gameObject.GetComponent<UISprite>();
        //Spt_BGSprite = _uiRoot.transform.FindChild("UnionInfo/UnionInfoAnim/BGSprite").gameObject.GetComponent<UISprite>();
        //Spt_ContextBGSprite = _uiRoot.transform.FindChild("UnionInfo/UnionInfoAnim/ContextBGSprite").gameObject.GetComponent<UISprite>();
        //Lbl_TitleLabel = _uiRoot.transform.FindChild("UnionInfo/UnionInfoAnim/TitleGroup/TitleLabel").gameObject.GetComponent<UILabel>();
        //Spt_TitleLeftSprite = _uiRoot.transform.FindChild("UnionInfo/UnionInfoAnim/TitleGroup/TitleLeftSprite").gameObject.GetComponent<UISprite>();
        //Spt_TitleRightSprite = _uiRoot.transform.FindChild("UnionInfo/UnionInfoAnim/TitleGroup/TitleRightSprite").gameObject.GetComponent<UISprite>();
        //Spt_NameBGSprite1 = _uiRoot.transform.FindChild("UnionInfo/UnionInfoAnim/Name/NameBGSprite1").gameObject.GetComponent<UISprite>();
        //Spt_NameBGSprite2 = _uiRoot.transform.FindChild("UnionInfo/UnionInfoAnim/Name/NameBGSprite2").gameObject.GetComponent<UISprite>();
        Lbl_UnionNameLabel = _uiRoot.transform.FindChild("UnionInfo/UnionInfoAnim/Name/UnionNameLabel").gameObject.GetComponent<UILabel>();
        Lbl_UnionLevelLabel = _uiRoot.transform.FindChild("UnionInfo/UnionInfoAnim/Name/UnionLevelLabel").gameObject.GetComponent<UILabel>();
        Spt_IconFrame = _uiRoot.transform.FindChild("UnionInfo/UnionInfoAnim/Icon/IconFrame").gameObject.GetComponent<UISprite>();
        Spt_IconBG = _uiRoot.transform.FindChild("UnionInfo/UnionInfoAnim/Icon/IconBG").gameObject.GetComponent<UISprite>();
        Spt_IconSprite = _uiRoot.transform.FindChild("UnionInfo/UnionInfoAnim/Icon/IconSprite").gameObject.GetComponent<UISprite>();
        //Lbl_PopulationLabel = _uiRoot.transform.FindChild("UnionInfo/UnionInfoAnim/PopulationLabel").gameObject.GetComponent<UILabel>();
        Lbl_PopulationtnContent = _uiRoot.transform.FindChild("UnionInfo/UnionInfoAnim/PopulationtnContent").gameObject.GetComponent<UILabel>();
        //Lbl_MaterialLabel = _uiRoot.transform.FindChild("UnionInfo/UnionInfoAnim/MaterialLabel").gameObject.GetComponent<UILabel>();
        Lbl_MaterialContent = _uiRoot.transform.FindChild("UnionInfo/UnionInfoAnim/MaterialContent").gameObject.GetComponent<UILabel>();
        //Lbl_NormalTerritoryLabel = _uiRoot.transform.FindChild("UnionInfo/UnionInfoAnim/NormalTerritoryLabel").gameObject.GetComponent<UILabel>();
        Lbl_NormalTerritoryContent = _uiRoot.transform.FindChild("UnionInfo/UnionInfoAnim/NormalTerritoryContent").gameObject.GetComponent<UILabel>();
        //Lbl_SpecialTerritoryLabel = _uiRoot.transform.FindChild("UnionInfo/UnionInfoAnim/SpecialTerritoryLabel").gameObject.GetComponent<UILabel>();
        Lbl_SpecialTerritoryContent = _uiRoot.transform.FindChild("UnionInfo/UnionInfoAnim/SpecialTerritoryContent").gameObject.GetComponent<UILabel>();
        //Lbl_FightTerritoryLabel = _uiRoot.transform.FindChild("UnionInfo/UnionInfoAnim/FightTerritoryLabel").gameObject.GetComponent<UILabel>();
        Lbl_FightTerritoryContent = _uiRoot.transform.FindChild("UnionInfo/UnionInfoAnim/FightTerritoryContent").gameObject.GetComponent<UILabel>();
        //Lbl_MinProductionLabel = _uiRoot.transform.FindChild("UnionInfo/UnionInfoAnim/MinProductionLabel").gameObject.GetComponent<UILabel>();
        Lbl_MinProdutionContent = _uiRoot.transform.FindChild("UnionInfo/UnionInfoAnim/MinProdutionContent").gameObject.GetComponent<UILabel>();
        //Lbl_MaxProductionLabel = _uiRoot.transform.FindChild("UnionInfo/UnionInfoAnim/MaxProductionLabel").gameObject.GetComponent<UILabel>();
        //Lbl_MaxProdutionContent = _uiRoot.transform.FindChild("UnionInfo/UnionInfoAnim/MaxProdutionContent").gameObject.GetComponent<UILabel>();
        //Lbl_SpecialProductionLabel = _uiRoot.transform.FindChild("UnionInfo/UnionInfoAnim/SpecialProductionLabel").gameObject.GetComponent<UILabel>();
        Btn_DetailInfoButton = _uiRoot.transform.FindChild("UnionInfo/UnionInfoAnim/DetailInfoButton").gameObject.GetComponent<UIButton>();
        //Spt_DetailInfoButton = _uiRoot.transform.FindChild("UnionInfo/UnionInfoAnim/DetailInfoButton").gameObject.GetComponent<UISprite>();
        //Lbl_BtnDetailInfoButtonDetailInfoSprite = _uiRoot.transform.FindChild("UnionInfo/UnionInfoAnim/DetailInfoButton/DetailInfoSprite").gameObject.GetComponent<UILabel>();
        //Spt_CloseRuleButton = _uiRoot.transform.FindChild("UnionInfo/UnionInfoAnim/CloseRuleButton").gameObject.GetComponent<UISprite>();
        Btn_CloseUnionInfoButton = _uiRoot.transform.FindChild("UnionInfo/UnionInfoAnim/CloseUnionInfoButton").gameObject.GetComponent<UIButton>();

        //=====================================================================================特殊产出
        Gobj_SpecialProduction = _uiRoot.transform.FindChild("SpecialProductionInfo").gameObject;
        //UIPanel_SpecialProductionInfo = _uiRoot.transform.FindChild("SpecialProductionInfo").gameObject.GetComponent<UIPanel>();
        Spt_SPInfoMask = _uiRoot.transform.FindChild("SpecialProductionInfo/SPInfoMask").gameObject.GetComponent<UISprite>();
        //Spt_BGSprite = _uiRoot.transform.FindChild("SpecialProductionInfo/SPInfoAnim/BGSprite").gameObject.GetComponent<UISprite>();
        //Spt_ContextBGSprite = _uiRoot.transform.FindChild("SpecialProductionInfo/SPInfoAnim/ContextBGSprite").gameObject.GetComponent<UISprite>();
        //Lbl_TitleLabel = _uiRoot.transform.FindChild("SpecialProductionInfo/SPInfoAnim/TitleGroup/TitleLabel").gameObject.GetComponent<UILabel>();
        //Spt_TitleLeftSprite = _uiRoot.transform.FindChild("SpecialProductionInfo/SPInfoAnim/TitleGroup/TitleLeftSprite").gameObject.GetComponent<UISprite>();
        //Spt_TitleRightSprite = _uiRoot.transform.FindChild("SpecialProductionInfo/SPInfoAnim/TitleGroup/TitleRightSprite").gameObject.GetComponent<UISprite>();
        //Spt_TitleBarSprite = _uiRoot.transform.FindChild("SpecialProductionInfo/SPInfoAnim/TitleBarSprite").gameObject.GetComponent<UISprite>();
        //Lbl_TileIDTitle = _uiRoot.transform.FindChild("SpecialProductionInfo/SPInfoAnim/TitleBarSprite/TileIDTitle").gameObject.GetComponent<UILabel>();
        //Lbl_ProductionsTitle = _uiRoot.transform.FindChild("SpecialProductionInfo/SPInfoAnim/TitleBarSprite/ProductionsTitle").gameObject.GetComponent<UILabel>();
        //Lbl_OwnerStateTitle = _uiRoot.transform.FindChild("SpecialProductionInfo/SPInfoAnim/TitleBarSprite/OwnerStateTitle").gameObject.GetComponent<UILabel>();
        //Spt_CloseRuleButton = _uiRoot.transform.FindChild("SpecialProductionInfo/SPInfoAnim/CloseRuleButton").gameObject.GetComponent<UISprite>();
        Gobj_OutputItem = _uiRoot.transform.FindChild("SpecialProductionInfo/SPInfoAnim/OutputItem").gameObject;
        Btn_CloseSPOutputButton = _uiRoot.transform.FindChild("SpecialProductionInfo/SPInfoAnim/CloseSPOutputButton").gameObject.GetComponent<UIButton>();
        //Lbl_OwnerState = _uiRoot.transform.FindChild("SpecialProductionInfo/SPInfoAnim/OutputItem/OwnerState").gameObject.GetComponent<UILabel>();
        //Lbl_Productions = _uiRoot.transform.FindChild("SpecialProductionInfo/SPInfoAnim/OutputItem/Productions").gameObject.GetComponent<UILabel>();
        //Lbl_TileID = _uiRoot.transform.FindChild("SpecialProductionInfo/SPInfoAnim/OutputItem/TileID").gameObject.GetComponent<UILabel>();
        UIPanel_DetailInformation = _uiRoot.transform.FindChild("SpecialProductionInfo/SPInfoAnim/DetailInformation").gameObject.GetComponent<UIPanel>();
        //ScrView_DetailInformation = _uiRoot.transform.FindChild("SpecialProductionInfo/SPInfoAnim/DetailInformation").gameObject.GetComponent<UIScrollView>();
        Table_UnionOutputTable = _uiRoot.transform.FindChild("SpecialProductionInfo/SPInfoAnim/DetailInformation/UnionOutputTable").gameObject.GetComponent<UITable>();

        //======================================================================================跨服（奖励）信息
        Gobj_ServerInfo = _uiRoot.transform.FindChild("ServerInfo").gameObject;
        //UIPanel_ServerInfo = _uiRoot.transform.FindChild("ServerInfo").gameObject.GetComponent<UIPanel>();
        //Spt_TitleRightBG = _uiRoot.transform.FindChild("ServerInfo/ServerInfoAnim/TitleObj/TitleRightBG").gameObject.GetComponent<UISprite>();
        //Spt_TitleLiftBG = _uiRoot.transform.FindChild("ServerInfo/ServerInfoAnim/TitleObj/TitleLiftBG").gameObject.GetComponent<UISprite>();
        Lbl_ServerTitle = _uiRoot.transform.FindChild("ServerInfo/ServerInfoAnim/TitleObj/ServerTitle").gameObject.GetComponent<UILabel>();
        //Spt_CloseTileInfoButton = _uiRoot.transform.FindChild("ServerInfo/ServerInfoAnim/CloseTileInfoButton").gameObject.GetComponent<UISprite>();
        Btn_CloseServerInfoButton = _uiRoot.transform.FindChild("ServerInfo/ServerInfoAnim/CloseServerInfoButton").gameObject.GetComponent<UIButton>();
        //Spt_BG = _uiRoot.transform.FindChild("ServerInfo/ServerInfoAnim/BG").gameObject.GetComponent<UISprite>();
        //Spt_ServerListBG = _uiRoot.transform.FindChild("ServerInfo/ServerInfoAnim/ServerListBlock/ServerListBG").gameObject.GetComponent<UISprite>();
        //Spt_ServerTitleBG = _uiRoot.transform.FindChild("ServerInfo/ServerInfoAnim/ServerListBlock/ServerTitleBG").gameObject.GetComponent<UISprite>();
        //Lbl_ServerNameTitle = _uiRoot.transform.FindChild("ServerInfo/ServerInfoAnim/ServerListBlock/ServerNameTitle").gameObject.GetComponent<UILabel>();
        Gobj_ServerListBlock = _uiRoot.transform.FindChild("ServerInfo/ServerInfoAnim/ServerListBlock").gameObject;
        Lbl_ServerName = _uiRoot.transform.FindChild("ServerInfo/ServerInfoAnim/ServerListBlock/ServerName").gameObject.GetComponent<UILabel>();
        //UIPanel_ServerList = _uiRoot.transform.FindChild("ServerInfo/ServerInfoAnim/ServerListBlock/ServerList").gameObject.GetComponent<UIPanel>();
        //ScrView_ServerList = _uiRoot.transform.FindChild("ServerInfo/ServerInfoAnim/ServerListBlock/ServerList").gameObject.GetComponent<UIScrollView>();
        Grd_ServerListGrid = _uiRoot.transform.FindChild("ServerInfo/ServerInfoAnim/ServerListBlock/ServerList/ServerListGrid").gameObject.GetComponent<UIGrid>();
        Trans_AwardListBlock = _uiRoot.transform.FindChild("ServerInfo/ServerInfoAnim/AwardListBlock");
        Spt_AwardListBG = _uiRoot.transform.FindChild("ServerInfo/ServerInfoAnim/AwardListBlock/AwardListBG").gameObject.GetComponent<UISprite>();
        Spt_AwardTitleBG = _uiRoot.transform.FindChild("ServerInfo/ServerInfoAnim/AwardListBlock/AwardTitleBG").gameObject.GetComponent<UISprite>();
        Lbl_TitleAward = _uiRoot.transform.FindChild("ServerInfo/ServerInfoAnim/AwardListBlock/TitleAward").gameObject.GetComponent<UILabel>();
        Btn_BattleAward = _uiRoot.transform.FindChild("ServerInfo/ServerInfoAnim/AwardListBlock/BattleAward").gameObject.GetComponent<UIButton>();
        Spt_BtnBattleAwardBattleAwardBtn = _uiRoot.transform.FindChild("ServerInfo/ServerInfoAnim/AwardListBlock/BattleAward/BattleAwardBtn").gameObject.GetComponent<UISprite>();
        Lbl_BtnBattleAwardLabel = _uiRoot.transform.FindChild("ServerInfo/ServerInfoAnim/AwardListBlock/BattleAward/Label").gameObject.GetComponent<UILabel>();
        Btn_SeasonAward = _uiRoot.transform.FindChild("ServerInfo/ServerInfoAnim/AwardListBlock/SeasonAward").gameObject.GetComponent<UIButton>();
        Spt_BtnSeasonAwardSeasonAwardBtn = _uiRoot.transform.FindChild("ServerInfo/ServerInfoAnim/AwardListBlock/SeasonAward/SeasonAwardBtn").gameObject.GetComponent<UISprite>();
        Lbl_BtnSeasonAwardLabel = _uiRoot.transform.FindChild("ServerInfo/ServerInfoAnim/AwardListBlock/SeasonAward/Label").gameObject.GetComponent<UILabel>();
        Lbl_RankingLabel = _uiRoot.transform.FindChild("ServerInfo/ServerInfoAnim/AwardListBlock/RankingAwardsItem/RankingLabel").gameObject.GetComponent<UILabel>();
        Gobj_RankingAwardItem = _uiRoot.transform.FindChild("ServerInfo/ServerInfoAnim/AwardListBlock/RankingAwardsItem").gameObject;
        Grd_RankingGoods = _uiRoot.transform.FindChild("ServerInfo/ServerInfoAnim/AwardListBlock/RankingAwardsItem/RankingGoods").gameObject.GetComponent<UIGrid>();
        //UIPanel_ShowAwards = _uiRoot.transform.FindChild("ServerInfo/ServerInfoAnim/AwardListBlock/ShowAwards").gameObject.GetComponent<UIPanel>();
        ScrView_ShowAwards = _uiRoot.transform.FindChild("ServerInfo/ServerInfoAnim/AwardListBlock/ShowAwards").gameObject.GetComponent<UIScrollView>();
        UITable_Table = _uiRoot.transform.FindChild("ServerInfo/ServerInfoAnim/AwardListBlock/ShowAwards/Table").gameObject.GetComponent<UITable>();
        //Spt_BulletinBoardBg = _uiRoot.transform.FindChild("ServerInfo/ServerInfoAnim/BulletinBoardBg").gameObject.GetComponent<UISprite>();
        Lbl_Bulletin = _uiRoot.transform.FindChild("ServerInfo/ServerInfoAnim/BulletinBoardBg/Bulletin").gameObject.GetComponent<UILabel>();
        Spt_ServerInfoMask = _uiRoot.transform.FindChild("ServerInfo/ServerInfoMask").gameObject.GetComponent<UISprite>();

        //==============================================================================================================(地块)战场信息
        Gobj_StageInfo = _uiRoot.transform.FindChild("StageInfo").gameObject;
        Btn_StageClose = _uiRoot.transform.FindChild("StageInfo/StageInfoAnim/Close").gameObject.GetComponent<UIButton>();
        Lbl_TypeTitle = _uiRoot.transform.FindChild("StageInfo/StageInfoAnim/TitleGroup/TitleLabel").gameObject.GetComponent<UILabel>();
        Lbl_StageDesc = _uiRoot.transform.FindChild("StageInfo/StageInfoAnim/DescGroup/StageDesc").gameObject.GetComponent<UILabel>();
        Grd_EnemyGrid = _uiRoot.transform.FindChild("StageInfo/StageInfoAnim/EnemyGroup/EnemyGrid").gameObject.GetComponent<UIGrid>();
        Gobj_Enemy = _uiRoot.transform.FindChild("StageInfo/StageInfoAnim/EnemyGroup/EnemyGrid/gobj_EnemyInfoComp").gameObject;
        Spt_StageInfoMask = _uiRoot.transform.FindChild("StageInfo/StageInfoMask").gameObject.GetComponent<UISprite>();
        Btn_ReadyBattle = _uiRoot.transform.FindChild("StageInfo/StageInfoAnim/ReadyBattleGroup/ReadyBattle").gameObject.GetComponent<UIButton>();
        Lbl_GateCount = _uiRoot.transform.FindChild("StageInfo/StageInfoAnim/gobj_GateCountGroup/GateCountLabel").gameObject.GetComponent<UILabel>();
        Lbl_CorpsName = _uiRoot.transform.FindChild("StageInfo/StageInfoAnim/gobj_IntegralGroup/gobj_TopRank/CorpsName").gameObject.GetComponent<UILabel>();
        Lbl_MyIntegralNum = _uiRoot.transform.FindChild("StageInfo/StageInfoAnim/gobj_IntegralGroup/gobj_MyIntegral/MyIntegralNum").gameObject.GetComponent<UILabel>();
        Lbl_IntegralNum = _uiRoot.transform.FindChild("StageInfo/StageInfoAnim/gobj_IntegralGroup/gobj_Integral/IntegralNum").gameObject.GetComponent<UILabel>();
        //==============================================================================================================奖励物品
        Gobj_AwardGoods = _uiRoot.transform.FindChild("AwardItem").gameObject;

    }

    public void SetLabelValues()
    {
        /*
        Lbl_BtnRankListButtonRankListLabel.text = "排行";
        Lbl_BtnRuleButtonRuleLabel.text = "规则";
        Lbl_BattleCountdownDesc.text = "15:55:55 后战役结束";
        Lbl_RestCountdownDesc.text = "00:04:59 后修整完毕";
        Lbl_BtnSearchButtonSearchLabel.text = "查找";
        Lbl_InputSearchTileSearchID.text = "99999999999";
        Lbl_RuleDesc.text = "hgyuikuycjhkkkkkkkkkkyg,hvhujkfyfluky gjhvuk fiutfcyhggggggggggggggggggggggggguk,vhgyuikuycjhkkkkkkkkkkyg,hvhujkfyfluky gjhvuk fiutfcyhggggggggggggggggggggggggguk,vhgyuikuycjhkkkkkkkkkkyg,hvhujkfyfluky gjhvuk fiutfcyhggggggggggggggggggggggggguk,vhgyuikuycjhkkkkkkkkkkyg,hvhujkfyfluky gjhvuk fiutfcyhggggggggggggggggggggggggguk,vhgyuikuycjhkkkkkkkkkkyg,hvhujkfyfluky gjhvuk fiutfcyhggggggggggggggggggggggggguk,vhgyuikuycjhkkkkkkkkkkyg,hvhujkfyfluky gjhvuk fiutfcyhggggggggggggggggggggggggguk,vhgyuikuycjhkkkkkkkkkkyg,hvhujkfyfluky gjhvuk fiutfcyhggggggggggggggggggggggggguk,vhgyuikuycjhkkkkkkkkkkyg,hvhujkfyfluky gjhvuk fiutfcyhggggggggggggggggggggggggguk,vhgyuikuycjhkkkkkkkkkkyg,hvhujkfyfluky gjhvuk fiutfcyhggggggggggggggggggggggggguk,vhgyuikuycjhkkkkkkkkkkyg,hvhujkfyfluky gjhvuk fiutfcyhggggggggggggggggggggggggguk,vhgyuikuycjhkkkkkkkkkkyg,hvhujkfyfluky gjhvuk fiutfcyhggggggggggggggggggggggggguk,vhgyuikuycjhkkkkkkkkkkyg,hvhujkfyfluky gjhvuk fiutfcyhggggggggggggggggggggggggguk,vhgyuikuycjhkkkkkkkkkkyg,hvhujkfyfluky gjhvuk fiutfcyhggggggggggggggggggggggggguk,vhgyuikuycjhkkkkkkkkkkyg,hvhujkfyfluky gjhvuk fiutfcyhggggggggggggggggggggggggguk,vhgyuikuycjhkkkkkkkkkkyg,hvhujkfyfluky gjhvuk fiutfcyhggggggggggggggggggggggggguk,vhgyuikuycjhkkkkkkkkkkyg,hvhujkfyfluky gjhvuk fiutfcyhggggggggggggggggggggggggguk,vhgyuikuycjhkkkkkkkkkkyg,hvhujkfyfluky gjhvuk fiutfcyhggggggggggggggggggggggggguk,vhgyuikuycjhkkkkkkkkkkyg,hvhujkfyfluky gjhvuk fiutfcyhggggggggggggggggggggggggguk,vhgyuikuycjhkkkkkkkkkkyg,hvhujkfyfluky gjhvuk fiutfcyhggggggggggggggggggggggggguk,v";
        Lbl_TitleLabel.text = "规则";
        Lbl_TileTitle.text = "空地";
        Lbl_TitleScore.text = "积分";
        Lbl_TitleName.text = "军团名";
        Lbl_TitleRank.text = "名次";
        Lbl_TitleAward.text = "地块信息";
        Lbl_Rank.text = "1";
        Lbl_Name.text = "角色名六个字";
        Lbl_Score.text = "99999999";
        Lbl_Rank.text = "";
        Lbl_Name.text = "";
        Lbl_Score.text = "";
        Lbl_BtnUnionRankLabel.text = "军团排名";
        Lbl_BtnPersonRankLabel.text = "成员排名";
        Lbl_TileIDLabel.text = "编号:";
        Lbl_TileIDContent.text = "A89";
        Lbl_OwnerLabel.text = "所属:";
        Lbl_OwnerContent.text = "无主之地";
        Lbl_StateLabel.text = "状态:";
        Lbl_StateContent.text = "交战地";
        Lbl_MilitarySuppliesLabel.text = "军需产出:";
        Lbl_MilitarySuppliesContent.text = "5000";
        Lbl_ControlTurnsLabel.text = "占领场次:";
        Lbl_ControlTurnstContent.text = "未被占领";
        Lbl_SpecialProdutionLabel.text = "特殊产出:";
        Lbl_Num.text = "X11";
        Lbl_Num.text = "X11";
        Lbl_Num.text = "X11";
        Lbl_FightCDTip.text = "[E3A94B]军队需要休整[5AE46B]00:04:59[-]才能继续出战[-]";
        Lbl_BtnFightLabel.text = "出战";
        Lbl_TitleLabel.text = "军团信息";
        Lbl_UnionNameLabel.text = "军团没有名字";
        Lbl_UnionLevelLabel.text = "等级：10";
        Lbl_PopulationLabel.text = "军团人数：";
        Lbl_PopulationtnContent.text = "5/50";
        Lbl_MaterialLabel.text = "当前物资：";
        Lbl_MaterialContent.text = "5555555";
        Lbl_NormalTerritoryLabel.text = "一般领地：";
        Lbl_NormalTerritoryContent.text = "10";
        Lbl_SpecialTerritoryLabel.text = "特殊领地：";
        Lbl_SpecialTerritoryContent.text = "2";
        Lbl_FightTerritoryLabel.text = "交战领地：";
        Lbl_FightTerritoryContent.text = "23";
        Lbl_MinProductionLabel.text = "最低产出：";
        Lbl_MinProdutionContent.text = "233";
        Lbl_MaxProductionLabel.text = "最高产出：";
        Lbl_MaxProdutionContent.text = "2333";
        Lbl_SpecialProductionLabel.text = "特殊产出：";
        Lbl_BtnDetailInfoButtonDetailInfoSprite.text = "详细";
        Lbl_TitleLabel.text = "特殊产出";
        Lbl_TileIDTitle.text = "地块编号";
        Lbl_ProductionsTitle.text = "产出";
        Lbl_OwnerStateTitle.text = "状态";
        Lbl_OwnerState.text = "已占领";
        Lbl_Productions.text = "AK-47 X233";
        Lbl_TileID.text = "S9900";
        Lbl_ServerTitle.text = "奖励信息";
        Lbl_ServerNameTitle.text = "参与服务器:";
        Lbl_ServerName.text = "123142312352";
        Lbl_TitleAward.text = "--战役奖励--";
        Lbl_BtnBattleAwardLabel.text = "战役";
        Lbl_BtnSeasonAwardLabel.text = "赛季";
        Lbl_RankingLabel.text = "1-1000物资";
        Lbl_GoodsNum.text = "X11";
        Lbl_Bulletin.text = "第x场战役将在59:59:59后开";
        */
    }

    public void Uninitialize()
    {

    }

    public void SetVisible(bool isVisible)
    {
         _uiRoot.SetActive(isVisible);
    }

}
